/**
 * Typed access to the Artemis Studio API.
 *
 * DTO types come from `schema.d.ts`, generated by `openapi-typescript` from the
 * backend's committed OpenAPI snapshot (`web/openapi.json`) — ADR-0019. Do not
 * hand-write DTO interfaces here; add `@Schema` on the Java DTO and regenerate
 * (`npm run gen:api`). `ApiError` (RFC 9457 parsing) and the query-key helpers
 * are the only non-generated pieces.
 */
import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseQueryResult,
} from '@tanstack/react-query';
import type { components } from './schema.d.ts';

const BASE = '/api/v1';

type Schemas = components['schemas'];

// ── generated DTO aliases ──────────────────────────────────────────────────

export type CapabilityView = Schemas['CapabilityView'];
export type CapabilitiesView = Schemas['CapabilitiesView'];
export type NodeEndpointView = Schemas['NodeEndpointView'];
export type LogicalNodeView = Schemas['LogicalNodeView'];
export type TopologyView = Schemas['TopologyView'];
export type HealthView = Schemas['HealthView'];
export type ClusterSummary = Schemas['ClusterSummary'];
export type ClusterDetail = Schemas['ClusterDetail'];
export type RegisterPreview = Schemas['RegisterPreview'];
export type RegisterClusterRequest = Schemas['RegisterClusterRequest'];
export type QueueView = Schemas['QueueView'];
export type QueueNodeCell = Schemas['QueueNodeCell'];
export type AddressView = Schemas['AddressView'];
export type ConsumerView = Schemas['ConsumerView'];
export type SessionView = Schemas['SessionView'];
export type ConnectionView = Schemas['ConnectionView'];
export type ProducerView = Schemas['ProducerView'];
export type SettingValue = Schemas['SettingValue'];
export type SettingsResponse = Schemas['SettingsResponse'];
export type MessageSummaryView = Schemas['MessageSummaryView'];
export type MessageDetailView = Schemas['MessageDetailView'];
export type MessagePageView = Schemas['MessagePageView'];
export type AffectedView = Schemas['AffectedView'];
export type DryRunView = Schemas['DryRunView'];
export type SendMessageRequest = Schemas['SendMessageRequest'];
export type MessageActionRequest = Schemas['MessageActionRequest'];
export type MessageActionKind = 'move' | 'retry' | 'delete' | 'expire';
export type AuditEventView = Schemas['AuditEventView'];
export type AuditPageView = Schemas['AuditPageView'];
export type DlqView = Schemas['DlqView'];
export type DlqAddress = Schemas['DlqAddress'];
export type DlqQueue = Schemas['DlqQueue'];

/** String enums the backend serialises as bare strings; narrowed here for the UI. */
export type CapabilityStatus = 'AVAILABLE' | 'UNAVAILABLE' | 'UNKNOWN';
export type SplitBrain = 'NONE' | 'SUSPECTED' | 'CRITICAL';
export type HealthLevel = 'OK' | 'DEGRADED' | 'CRITICAL' | 'UNKNOWN';

/** Generic paged envelope (`PagedView<T>` on the backend). */
export interface PagedView<T> {
  data: T[];
  count: number;
  page: number;
  pageSize: number;
}

// ── error + transport ──────────────────────────────────────────────────────

/** A parsed `application/problem+json` body. */
export class ApiError extends Error {
  readonly status: number;
  readonly type: string;
  readonly title: string;
  readonly brokerErrorKind?: string;
  readonly fieldErrors: { field: string; message: string }[];

  constructor(status: number, body: Record<string, unknown>) {
    super(
      (body.detail as string) ??
        (body.title as string) ??
        `Request failed (${status})`,
    );
    this.name = 'ApiError';
    this.status = status;
    this.type = (body.type as string) ?? 'about:blank';
    this.title = (body.title as string) ?? 'Error';
    this.brokerErrorKind = body.brokerErrorKind as string | undefined;
    this.fieldErrors =
      (body.errors as { field: string; message: string }[] | undefined) ?? [];
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    headers: { 'content-type': 'application/json', ...init?.headers },
    ...init,
  });
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  const body = text ? JSON.parse(text) : {};
  if (!res.ok) throw new ApiError(res.status, body);
  return body as T;
}

// ── query keys ─────────────────────────────────────────────────────────────

export type ResourceKind =
  | 'queues'
  | 'addresses'
  | 'consumers'
  | 'sessions'
  | 'connections'
  | 'producers';

export interface ResourceParams {
  q?: string;
  sort?: string;
  page?: number;
  size?: number;
}

function resourceSearch(params: ResourceParams): string {
  const sp = new URLSearchParams();
  if (params.q) sp.set('q', params.q);
  if (params.sort) sp.set('sort', params.sort);
  if (params.page && params.page > 1) sp.set('page', String(params.page));
  if (params.size) sp.set('size', String(params.size));
  const s = sp.toString();
  return s ? `?${s}` : '';
}

export const keys = {
  all: ['clusters'] as const,
  detail: (id: string) => ['clusters', id] as const,
  topology: (id: string) => ['clusters', id, 'topology'] as const,
  health: (id: string) => ['clusters', id, 'health'] as const,
  resource: (id: string, kind: ResourceKind, params: ResourceParams = {}) =>
    ['clusters', id, kind, params] as const,
  /** The TanStack Query key a stream topic invalidates. */
  topic: (id: string, topic: 'topology' | 'health' | 'queues') => {
    if (topic === 'topology') return ['clusters', id, 'topology'] as const;
    if (topic === 'health') return ['clusters', id, 'health'] as const;
    return ['clusters', id, 'queues'] as const;
  },
  messages: (
    id: string,
    queueName: string,
    params: MessageBrowseParams = {},
  ) => ['clusters', id, 'queues', queueName, 'messages', params] as const,
  message: (id: string, queueName: string, messageId: string, node?: string, filter?: string) =>
    ['clusters', id, 'queues', queueName, 'messages', messageId, { node, filter }] as const,
};

// ── queries ────────────────────────────────────────────────────────────────

export function useClusters(): UseQueryResult<ClusterSummary[], ApiError> {
  return useQuery({
    queryKey: keys.all,
    queryFn: () => request<ClusterSummary[]>('/clusters'),
    refetchInterval: 5_000,
  });
}

export function useCluster(
  id: string | null,
): UseQueryResult<ClusterDetail, ApiError> {
  return useQuery({
    queryKey: id ? keys.detail(id) : ['clusters', 'none'],
    queryFn: () => request<ClusterDetail>(`/clusters/${id}`),
    enabled: id !== null,
    refetchInterval: 5_000,
  });
}

export function useTopology(id: string): UseQueryResult<TopologyView, ApiError> {
  return useQuery({
    queryKey: keys.topology(id),
    queryFn: () => request<TopologyView>(`/clusters/${id}/topology`),
    refetchInterval: 5_000,
  });
}

export function useHealth(id: string): UseQueryResult<HealthView, ApiError> {
  return useQuery({
    queryKey: keys.health(id),
    queryFn: () => request<HealthView>(`/clusters/${id}/health`),
    refetchInterval: 5_000,
  });
}

export function useQueues(
  id: string,
  params: ResourceParams = {},
): UseQueryResult<PagedView<QueueView>, ApiError> {
  return useQuery({
    queryKey: keys.resource(id, 'queues', params),
    queryFn: () =>
      request<PagedView<QueueView>>(
        `/clusters/${id}/queues${resourceSearch(params)}`,
      ),
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

function useResource<T>(
  id: string,
  kind: ResourceKind,
  params: ResourceParams,
): UseQueryResult<PagedView<T>, ApiError> {
  return useQuery({
    queryKey: keys.resource(id, kind, params),
    queryFn: () =>
      request<PagedView<T>>(`/clusters/${id}/${kind}${resourceSearch(params)}`),
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

export const useAddresses = (id: string, p: ResourceParams = {}) =>
  useResource<AddressView>(id, 'addresses', p);
export const useConsumers = (id: string, p: ResourceParams = {}) =>
  useResource<ConsumerView>(id, 'consumers', p);
export const useSessions = (id: string, p: ResourceParams = {}) =>
  useResource<SessionView>(id, 'sessions', p);
export const useConnections = (id: string, p: ResourceParams = {}) =>
  useResource<ConnectionView>(id, 'connections', p);
export const useProducers = (id: string, p: ResourceParams = {}) =>
  useResource<ProducerView>(id, 'producers', p);

// ── mutations ──────────────────────────────────────────────────────────────

export function useCheckConnection() {
  return useMutation<RegisterPreview, ApiError, RegisterClusterRequest>({
    mutationFn: (body) =>
      request('/clusters?dryRun=true', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
  });
}

export function useRegisterCluster() {
  const qc = useQueryClient();
  return useMutation<ClusterDetail, ApiError, RegisterClusterRequest>({
    mutationFn: (body) =>
      request('/clusters', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

export function useRediscover(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<TopologyView, ApiError, void>({
    mutationFn: () =>
      request(`/clusters/${clusterId}/rediscover`, { method: 'POST' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.detail(clusterId) }),
  });
}

export function useOverrideNodeUrl(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<
    NodeEndpointView,
    ApiError,
    { nodeId: string; jolokiaUrl: string }
  >({
    mutationFn: ({ nodeId, jolokiaUrl }) =>
      request(`/clusters/${clusterId}/nodes/${nodeId}`, {
        method: 'PATCH',
        body: JSON.stringify({ jolokiaUrl }),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.detail(clusterId) }),
  });
}

export function useDeleteCluster() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (id) => request(`/clusters/${id}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

// ── settings ───────────────────────────────────────────────────────────────

const SETTINGS_KEY = ['settings'] as const;

export function useSettings(): UseQueryResult<SettingsResponse, ApiError> {
  return useQuery({
    queryKey: SETTINGS_KEY,
    queryFn: () => request<SettingsResponse>('/settings'),
  });
}

export function useUpdateSetting() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, { key: string; value: string }>({
    mutationFn: ({ key, value }) =>
      request(`/settings/${encodeURIComponent(key)}`, {
        method: 'PUT',
        body: JSON.stringify({ value }),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: SETTINGS_KEY }),
  });
}

export function useResetSetting() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (key) =>
      request(`/settings/${encodeURIComponent(key)}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: SETTINGS_KEY }),
  });
}

// ── messages (ADR-0021) ────────────────────────────────────────────────────

export interface MessageBrowseParams {
  node?: string;
  filter?: string;
  page?: number;
  size?: number;
}

function messageSearch(params: MessageBrowseParams): string {
  const sp = new URLSearchParams();
  if (params.node) sp.set('node', params.node);
  if (params.filter) sp.set('filter', params.filter);
  if (params.page && params.page > 1) sp.set('page', String(params.page));
  if (params.size) sp.set('size', String(params.size));
  const s = sp.toString();
  return s ? `?${s}` : '';
}

export function useMessages(
  clusterId: string,
  queueName: string,
  params: MessageBrowseParams = {},
): UseQueryResult<MessagePageView, ApiError> {
  return useQuery({
    queryKey: keys.messages(clusterId, queueName, params),
    queryFn: () =>
      request<MessagePageView>(
        `/clusters/${clusterId}/queues/${encodeURIComponent(queueName)}/messages${messageSearch(params)}`,
      ),
    placeholderData: (prev) => prev,
  });
}

export function useMessageDetail(
  clusterId: string,
  queueName: string,
  messageId: string | null,
  node?: string,
  filter?: string,
): UseQueryResult<MessageDetailView, ApiError> {
  return useQuery({
    queryKey: keys.message(clusterId, queueName, messageId ?? 'none', node, filter),
    queryFn: () => {
      const sp = new URLSearchParams();
      if (node) sp.set('node', node);
      if (filter) sp.set('filter', filter);
      const qs = sp.toString();
      return request<MessageDetailView>(
        `/clusters/${clusterId}/queues/${encodeURIComponent(queueName)}/messages/${messageId}${qs ? `?${qs}` : ''}`,
      );
    },
    enabled: messageId !== null,
  });
}

/** Extra `type` on `ApiError` for the 422 bulk-cap problem so the UI can show the count/cap. */
export interface BulkCapProblem {
  affectedCount: number;
  cap: number;
}

function messagesBase(clusterId: string, queueName: string) {
  return `/clusters/${clusterId}/queues/${encodeURIComponent(queueName)}/messages`;
}

function mutationQuery(node?: string, dryRun?: boolean, override?: boolean): string {
  const sp = new URLSearchParams();
  if (node) sp.set('node', node);
  if (dryRun) sp.set('dryRun', 'true');
  if (override) sp.set('override', 'true');
  const s = sp.toString();
  return s ? `?${s}` : '';
}

export interface SendVars {
  body: SendMessageRequest;
  node?: string;
  dryRun?: boolean;
}

export function useSendMessage(clusterId: string, queueName: string) {
  const qc = useQueryClient();
  return useMutation<AffectedView | DryRunView, ApiError, SendVars>({
    mutationFn: ({ body, node, dryRun }) =>
      request(`${messagesBase(clusterId, queueName)}${mutationQuery(node, dryRun)}`, {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    onSuccess: (result) => {
      // DryRunView carries `cap`; AffectedView does not. Only a real run changes state.
      if ('cap' in result) return;
      qc.invalidateQueries({ queryKey: keys.messages(clusterId, queueName) });
      qc.invalidateQueries({ queryKey: keys.topic(clusterId, 'queues') });
    },
  });
}

export interface ActionVars {
  action: MessageActionKind;
  body: MessageActionRequest;
  node?: string;
  dryRun?: boolean;
  override?: boolean;
}

export function useMessageAction(clusterId: string, queueName: string) {
  const qc = useQueryClient();
  return useMutation<AffectedView | DryRunView, ApiError, ActionVars>({
    mutationFn: ({ action, body, node, dryRun, override }) =>
      request(
        `${messagesBase(clusterId, queueName)}/actions/${action}${mutationQuery(node, dryRun, override)}`,
        { method: 'POST', body: JSON.stringify(body) },
      ),
    onSuccess: (result) => {
      // DryRunView carries `cap`; AffectedView does not. Only a real run changes state.
      if ('cap' in result) return;
      qc.invalidateQueries({ queryKey: keys.messages(clusterId, queueName) });
      qc.invalidateQueries({ queryKey: keys.topic(clusterId, 'queues') });
    },
  });
}

export interface PurgeVars {
  node?: string;
  dryRun?: boolean;
  override?: boolean;
}

export function usePurgeQueue(clusterId: string, queueName: string) {
  const qc = useQueryClient();
  return useMutation<AffectedView | DryRunView, ApiError, PurgeVars>({
    mutationFn: ({ node, dryRun, override }) =>
      request(`${messagesBase(clusterId, queueName)}${mutationQuery(node, dryRun, override)}`, {
        method: 'DELETE',
      }),
    onSuccess: (result) => {
      // DryRunView carries `cap`; AffectedView does not. Only a real run changes state.
      if ('cap' in result) return;
      qc.invalidateQueries({ queryKey: keys.messages(clusterId, queueName) });
      qc.invalidateQueries({ queryKey: keys.topic(clusterId, 'queues') });
    },
  });
}

// ── audit log (non-negotiable #3) ──────────────────────────────────────────

export interface AuditFilter {
  user?: string;
  action?: string;
  outcome?: string;
  from?: string;
  to?: string;
  page?: number;
  size?: number;
}

export function useAudit(
  clusterId: string,
  filter: AuditFilter = {},
): UseQueryResult<AuditPageView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'audit', filter],
    queryFn: () => {
      const sp = new URLSearchParams();
      for (const [k, v] of Object.entries(filter)) {
        if (v !== undefined && v !== '' && !(k === 'page' && v === 1)) sp.set(k, String(v));
      }
      const qs = sp.toString();
      return request<AuditPageView>(`/clusters/${clusterId}/audit${qs ? `?${qs}` : ''}`);
    },
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

export function useDlq(clusterId: string): UseQueryResult<DlqView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'dlq'],
    queryFn: () => request<DlqView>(`/clusters/${clusterId}/dlq`),
    refetchInterval: 10_000,
  });
}

export function useRotateCredentials(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<void, ApiError, { username: string; password: string }>({
    mutationFn: (body) =>
      request(`/clusters/${clusterId}/credentials`, {
        method: 'PUT',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.detail(clusterId) }),
  });
}
