/**
 * Typed access to the Artemis Studio API.
 *
 * DTO types come from `schema.d.ts`, generated by `openapi-typescript` from the
 * backend's committed OpenAPI snapshot (`web/openapi.json`) — ADR-0019. Do not
 * hand-write DTO interfaces here; add `@Schema` on the Java DTO and regenerate
 * (`npm run gen:api`). `ApiError` (RFC 9457 parsing) and the query-key helpers
 * are the only non-generated pieces.
 */
import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseQueryResult,
} from '@tanstack/react-query';
import type { components } from './schema.d.ts';

const BASE = '/api/v1';

type Schemas = components['schemas'];

// ── generated DTO aliases ──────────────────────────────────────────────────

export type CapabilityView = Schemas['CapabilityView'];
export type CapabilitiesView = Schemas['CapabilitiesView'];
export type NodeEndpointView = Schemas['NodeEndpointView'];
export type LogicalNodeView = Schemas['LogicalNodeView'];
export type TopologyView = Schemas['TopologyView'];
export type HealthView = Schemas['HealthView'];
export type ClusterSummary = Schemas['ClusterSummary'];
export type ClusterDetail = Schemas['ClusterDetail'];
export type RegisterPreview = Schemas['RegisterPreview'];
export type RegisterClusterRequest = Schemas['RegisterClusterRequest'];
export type QueueView = Schemas['QueueView'];
export type QueueNodeCell = Schemas['QueueNodeCell'];
export type AddressView = Schemas['AddressView'];
export type ConsumerView = Schemas['ConsumerView'];
export type SessionView = Schemas['SessionView'];
export type ConnectionView = Schemas['ConnectionView'];
export type ProducerView = Schemas['ProducerView'];
export type SettingValue = Schemas['SettingValue'];
export type SettingsResponse = Schemas['SettingsResponse'];
export type MessageSummaryView = Schemas['MessageSummaryView'];
export type MessageDetailView = Schemas['MessageDetailView'];
export type MessagePageView = Schemas['MessagePageView'];
export type AffectedView = Schemas['AffectedView'];
export type DryRunView = Schemas['DryRunView'];
export type SendMessageRequest = Schemas['SendMessageRequest'];
export type MessageActionRequest = Schemas['MessageActionRequest'];
export type MessageActionKind = 'move' | 'retry' | 'delete' | 'expire';
export type AuditEventView = Schemas['AuditEventView'];
export type AuditPageView = Schemas['AuditPageView'];
export type DlqView = Schemas['DlqView'];
export type DlqAddress = Schemas['DlqAddress'];
export type DlqQueue = Schemas['DlqQueue'];
export type BrokerEventView = Schemas['BrokerEventView'];
export type BrokerEventPageView = Schemas['BrokerEventPageView'];
export type ExpectationView = Schemas['ExpectationView'];
export type CreateExpectationRequest = Schemas['CreateExpectationRequest'];
export type UpdateExpectationRequest = Schemas['UpdateExpectationRequest'];
export type FlowView = Schemas['FlowView'];
export type FlowPageView = Schemas['FlowPageView'];
export type RrEventView = Schemas['RrEventView'];
export type AddressStatsView = Schemas['AddressStatsView'];
export type StatsResponse = Schemas['StatsResponse'];
export type MetricPoint = Schemas['MetricPoint'];
export type MetricSeries = Schemas['MetricSeries'];
export type MetricSeriesResponse = Schemas['MetricSeriesResponse'];
export type AlertRuleView = Schemas['AlertRuleView'];
export type AlertRuleRequest = Schemas['AlertRuleRequest'];
export type AlertFiringView = Schemas['AlertFiringView'];
export type AlertFiringPageView = Schemas['AlertFiringPageView'];
export type NotificationChannelView = Schemas['NotificationChannelView'];
export type NotificationChannelRequest = Schemas['NotificationChannelRequest'];
export type ClusterFiringCountView = Schemas['ClusterFiringCountView'];

// ── identity-and-sessions / authorization / environments / api-tokens / oidc-sso ──

export type LoginRequest = Schemas['LoginRequest'];
export type ChangePasswordRequest = Schemas['ChangePasswordRequest'];
export type MeView = Schemas['MeView'];
export type ProviderView = Schemas['ProviderView'];
export type GrantView = Schemas['GrantView'];
export type UserView = Schemas['UserView'];
export type CreateUserRequest = Schemas['CreateUserRequest'];
export type SetDisabledRequest = Schemas['SetDisabledRequest'];
export type GrantRequest = Schemas['GrantRequest'];
export type GrantSummary = Schemas['GrantSummary'];
export type RoleView = Schemas['RoleView'];
export type RoleRequest = Schemas['RoleRequest'];
export type PermissionView = Schemas['PermissionView'];
export type EnvironmentView = Schemas['EnvironmentView'];
export type EnvironmentRequest = Schemas['EnvironmentRequest'];
export type TokenView = Schemas['TokenView'];
export type CreatedTokenView = Schemas['CreatedTokenView'];
export type CreateTokenRequest = Schemas['CreateTokenRequest'];
export type TokenGrantRequest = Schemas['TokenGrantRequest'];
export type OidcMappingView = Schemas['OidcMappingView'];
export type OidcMappingRequest = Schemas['OidcMappingRequest'];

/** String enums the backend serialises as bare strings; narrowed here for the UI. */
export type CapabilityStatus = 'AVAILABLE' | 'UNAVAILABLE' | 'UNKNOWN';
export type SplitBrain = 'NONE' | 'SUSPECTED' | 'CRITICAL';
export type HealthLevel = 'OK' | 'DEGRADED' | 'CRITICAL' | 'UNKNOWN';

/** Generic paged envelope (`PagedView<T>` on the backend). */
export interface PagedView<T> {
  data: T[];
  count: number;
  page: number;
  pageSize: number;
}

// ── error + transport ──────────────────────────────────────────────────────

/** A parsed `application/problem+json` body. */
export class ApiError extends Error {
  readonly status: number;
  readonly type: string;
  readonly title: string;
  readonly brokerErrorKind?: string;
  readonly fieldErrors: { field: string; message: string }[];

  constructor(status: number, body: Record<string, unknown>) {
    super(
      (body.detail as string) ??
        (body.title as string) ??
        `Request failed (${status})`,
    );
    this.name = 'ApiError';
    this.status = status;
    this.type = (body.type as string) ?? 'about:blank';
    this.title = (body.title as string) ?? 'Error';
    this.brokerErrorKind = body.brokerErrorKind as string | undefined;
    this.fieldErrors =
      (body.errors as { field: string; message: string }[] | undefined) ?? [];
  }
}

/** Reads the `XSRF-TOKEN` cookie Spring Security's `CookieCsrfTokenRepository` sets (identity-and-sessions spec). */
function csrfToken(): string | undefined {
  return document.cookie
    .split('; ')
    .find((row) => row.startsWith('XSRF-TOKEN='))
    ?.split('=')[1];
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const method = (init?.method ?? 'GET').toUpperCase();
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (method !== 'GET' && method !== 'HEAD') {
    const token = csrfToken();
    if (token) headers['X-XSRF-TOKEN'] = token;
  }
  const res = await fetch(`${BASE}${path}`, {
    credentials: 'same-origin',
    headers: { ...headers, ...init?.headers },
    ...init,
  });
  if (res.status === 401 && !window.location.pathname.startsWith('/login')) {
    // The session expired or was never established — bounce to the login screen.
    // A full navigation (not client-side) so every in-flight query state resets.
    window.location.assign('/login');
  }
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  const body = text ? JSON.parse(text) : {};
  if (!res.ok) throw new ApiError(res.status, body);
  return body as T;
}

// ── query keys ─────────────────────────────────────────────────────────────

export type ResourceKind =
  | 'queues'
  | 'addresses'
  | 'consumers'
  | 'sessions'
  | 'connections'
  | 'producers';

export interface ResourceParams {
  q?: string;
  sort?: string;
  page?: number;
  size?: number;
}

function resourceSearch(params: ResourceParams): string {
  const sp = new URLSearchParams();
  if (params.q) sp.set('q', params.q);
  if (params.sort) sp.set('sort', params.sort);
  if (params.page && params.page > 1) sp.set('page', String(params.page));
  if (params.size) sp.set('size', String(params.size));
  const s = sp.toString();
  return s ? `?${s}` : '';
}

export const keys = {
  all: ['clusters'] as const,
  detail: (id: string) => ['clusters', id] as const,
  topology: (id: string) => ['clusters', id, 'topology'] as const,
  health: (id: string) => ['clusters', id, 'health'] as const,
  resource: (id: string, kind: ResourceKind, params: ResourceParams = {}) =>
    ['clusters', id, kind, params] as const,
  /** The TanStack Query key a signal stream topic invalidates (the `events` topic carries data, not a signal). */
  topic: (
    id: string,
    topic: 'topology' | 'health' | 'queues' | 'consumers' | 'sessions' | 'connections',
  ) => ['clusters', id, topic] as const,
  messages: (
    id: string,
    queueName: string,
    params: MessageBrowseParams = {},
  ) => ['clusters', id, 'queues', queueName, 'messages', params] as const,
  message: (id: string, queueName: string, messageId: string, node?: string, filter?: string) =>
    ['clusters', id, 'queues', queueName, 'messages', messageId, { node, filter }] as const,
  metrics: (id: string, params: MetricsParams) => ['clusters', id, 'metrics', params] as const,
  alertRules: (id: string) => ['clusters', id, 'alerts', 'rules'] as const,
  alertFiring: (id: string) => ['clusters', id, 'alerts', 'firing'] as const,
  alertHistory: (id: string, page: number, size: number) =>
    ['clusters', id, 'alerts', 'history', page, size] as const,
  channels: ['channels'] as const,
  firingCounts: ['alerts', 'firing'] as const,
  me: ['auth', 'me'] as const,
  authProviders: ['auth', 'providers'] as const,
  users: ['users'] as const,
  roles: ['roles'] as const,
  permissions: ['permissions'] as const,
  environments: ['environments'] as const,
  tokens: ['tokens'] as const,
  oidcMappings: ['oidc', 'mappings'] as const,
};

// ── queries ────────────────────────────────────────────────────────────────

export function useClusters(): UseQueryResult<ClusterSummary[], ApiError> {
  return useQuery({
    queryKey: keys.all,
    queryFn: () => request<ClusterSummary[]>('/clusters'),
    refetchInterval: 5_000,
  });
}

export function useCluster(
  id: string | null,
): UseQueryResult<ClusterDetail, ApiError> {
  return useQuery({
    queryKey: id ? keys.detail(id) : ['clusters', 'none'],
    queryFn: () => request<ClusterDetail>(`/clusters/${id}`),
    enabled: id !== null,
    refetchInterval: 5_000,
  });
}

export function useTopology(id: string): UseQueryResult<TopologyView, ApiError> {
  return useQuery({
    queryKey: keys.topology(id),
    queryFn: () => request<TopologyView>(`/clusters/${id}/topology`),
    refetchInterval: 5_000,
  });
}

export function useHealth(id: string): UseQueryResult<HealthView, ApiError> {
  return useQuery({
    queryKey: keys.health(id),
    queryFn: () => request<HealthView>(`/clusters/${id}/health`),
    refetchInterval: 5_000,
  });
}

export function useQueues(
  id: string,
  params: ResourceParams = {},
): UseQueryResult<PagedView<QueueView>, ApiError> {
  return useQuery({
    queryKey: keys.resource(id, 'queues', params),
    queryFn: () =>
      request<PagedView<QueueView>>(
        `/clusters/${id}/queues${resourceSearch(params)}`,
      ),
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

function useResource<T>(
  id: string,
  kind: ResourceKind,
  params: ResourceParams,
): UseQueryResult<PagedView<T>, ApiError> {
  return useQuery({
    queryKey: keys.resource(id, kind, params),
    queryFn: () =>
      request<PagedView<T>>(`/clusters/${id}/${kind}${resourceSearch(params)}`),
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

export const useAddresses = (id: string, p: ResourceParams = {}) =>
  useResource<AddressView>(id, 'addresses', p);
export const useConsumers = (id: string, p: ResourceParams = {}) =>
  useResource<ConsumerView>(id, 'consumers', p);
export const useSessions = (id: string, p: ResourceParams = {}) =>
  useResource<SessionView>(id, 'sessions', p);
export const useConnections = (id: string, p: ResourceParams = {}) =>
  useResource<ConnectionView>(id, 'connections', p);
export const useProducers = (id: string, p: ResourceParams = {}) =>
  useResource<ProducerView>(id, 'producers', p);

// ── mutations ──────────────────────────────────────────────────────────────

export function useCheckConnection() {
  return useMutation<RegisterPreview, ApiError, RegisterClusterRequest>({
    mutationFn: (body) =>
      request('/clusters?dryRun=true', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
  });
}

export function useRegisterCluster() {
  const qc = useQueryClient();
  return useMutation<ClusterDetail, ApiError, RegisterClusterRequest>({
    mutationFn: (body) =>
      request('/clusters', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

export function useRediscover(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<TopologyView, ApiError, void>({
    mutationFn: () =>
      request(`/clusters/${clusterId}/rediscover`, { method: 'POST' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.detail(clusterId) }),
  });
}

export function useOverrideNodeUrl(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<
    NodeEndpointView,
    ApiError,
    { nodeId: string; jolokiaUrl?: string; coreUrl?: string }
  >({
    mutationFn: ({ nodeId, jolokiaUrl, coreUrl }) =>
      request(`/clusters/${clusterId}/nodes/${nodeId}`, {
        method: 'PATCH',
        body: JSON.stringify({ jolokiaUrl, coreUrl }),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.detail(clusterId) }),
  });
}

export function useDeleteCluster() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (id) => request(`/clusters/${id}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

// ── settings ───────────────────────────────────────────────────────────────

const SETTINGS_KEY = ['settings'] as const;

export function useSettings(): UseQueryResult<SettingsResponse, ApiError> {
  return useQuery({
    queryKey: SETTINGS_KEY,
    queryFn: () => request<SettingsResponse>('/settings'),
  });
}

export function useUpdateSetting() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, { key: string; value: string }>({
    mutationFn: ({ key, value }) =>
      request(`/settings/${encodeURIComponent(key)}`, {
        method: 'PUT',
        body: JSON.stringify({ value }),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: SETTINGS_KEY }),
  });
}

export function useResetSetting() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (key) =>
      request(`/settings/${encodeURIComponent(key)}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: SETTINGS_KEY }),
  });
}

// ── messages (ADR-0021) ────────────────────────────────────────────────────

export interface MessageBrowseParams {
  node?: string;
  filter?: string;
  page?: number;
  size?: number;
}

function messageSearch(params: MessageBrowseParams): string {
  const sp = new URLSearchParams();
  if (params.node) sp.set('node', params.node);
  if (params.filter) sp.set('filter', params.filter);
  if (params.page && params.page > 1) sp.set('page', String(params.page));
  if (params.size) sp.set('size', String(params.size));
  const s = sp.toString();
  return s ? `?${s}` : '';
}

export function useMessages(
  clusterId: string,
  queueName: string,
  params: MessageBrowseParams = {},
): UseQueryResult<MessagePageView, ApiError> {
  return useQuery({
    queryKey: keys.messages(clusterId, queueName, params),
    queryFn: () =>
      request<MessagePageView>(
        `/clusters/${clusterId}/queues/${encodeURIComponent(queueName)}/messages${messageSearch(params)}`,
      ),
    placeholderData: (prev) => prev,
  });
}

export function useMessageDetail(
  clusterId: string,
  queueName: string,
  messageId: string | null,
  node?: string,
  filter?: string,
): UseQueryResult<MessageDetailView, ApiError> {
  return useQuery({
    queryKey: keys.message(clusterId, queueName, messageId ?? 'none', node, filter),
    queryFn: () => {
      const sp = new URLSearchParams();
      if (node) sp.set('node', node);
      if (filter) sp.set('filter', filter);
      const qs = sp.toString();
      return request<MessageDetailView>(
        `/clusters/${clusterId}/queues/${encodeURIComponent(queueName)}/messages/${messageId}${qs ? `?${qs}` : ''}`,
      );
    },
    enabled: messageId !== null,
  });
}

/** Extra `type` on `ApiError` for the 422 bulk-cap problem so the UI can show the count/cap. */
export interface BulkCapProblem {
  affectedCount: number;
  cap: number;
}

function messagesBase(clusterId: string, queueName: string) {
  return `/clusters/${clusterId}/queues/${encodeURIComponent(queueName)}/messages`;
}

function mutationQuery(node?: string, dryRun?: boolean, override?: boolean): string {
  const sp = new URLSearchParams();
  if (node) sp.set('node', node);
  if (dryRun) sp.set('dryRun', 'true');
  if (override) sp.set('override', 'true');
  const s = sp.toString();
  return s ? `?${s}` : '';
}

export interface SendVars {
  body: SendMessageRequest;
  node?: string;
  dryRun?: boolean;
}

export function useSendMessage(clusterId: string, queueName: string) {
  const qc = useQueryClient();
  return useMutation<AffectedView | DryRunView, ApiError, SendVars>({
    mutationFn: ({ body, node, dryRun }) =>
      request(`${messagesBase(clusterId, queueName)}${mutationQuery(node, dryRun)}`, {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    onSuccess: (result) => {
      // DryRunView carries `cap`; AffectedView does not. Only a real run changes state.
      if ('cap' in result) return;
      qc.invalidateQueries({ queryKey: keys.messages(clusterId, queueName) });
      qc.invalidateQueries({ queryKey: keys.topic(clusterId, 'queues') });
    },
  });
}

export interface ActionVars {
  action: MessageActionKind;
  body: MessageActionRequest;
  node?: string;
  dryRun?: boolean;
  override?: boolean;
}

export function useMessageAction(clusterId: string, queueName: string) {
  const qc = useQueryClient();
  return useMutation<AffectedView | DryRunView, ApiError, ActionVars>({
    mutationFn: ({ action, body, node, dryRun, override }) =>
      request(
        `${messagesBase(clusterId, queueName)}/actions/${action}${mutationQuery(node, dryRun, override)}`,
        { method: 'POST', body: JSON.stringify(body) },
      ),
    onSuccess: (result) => {
      // DryRunView carries `cap`; AffectedView does not. Only a real run changes state.
      if ('cap' in result) return;
      qc.invalidateQueries({ queryKey: keys.messages(clusterId, queueName) });
      qc.invalidateQueries({ queryKey: keys.topic(clusterId, 'queues') });
    },
  });
}

export interface PurgeVars {
  node?: string;
  dryRun?: boolean;
  override?: boolean;
}

export function usePurgeQueue(clusterId: string, queueName: string) {
  const qc = useQueryClient();
  return useMutation<AffectedView | DryRunView, ApiError, PurgeVars>({
    mutationFn: ({ node, dryRun, override }) =>
      request(`${messagesBase(clusterId, queueName)}${mutationQuery(node, dryRun, override)}`, {
        method: 'DELETE',
      }),
    onSuccess: (result) => {
      // DryRunView carries `cap`; AffectedView does not. Only a real run changes state.
      if ('cap' in result) return;
      qc.invalidateQueries({ queryKey: keys.messages(clusterId, queueName) });
      qc.invalidateQueries({ queryKey: keys.topic(clusterId, 'queues') });
    },
  });
}

// ── audit log (non-negotiable #3) ──────────────────────────────────────────

export interface AuditFilter {
  user?: string;
  action?: string;
  outcome?: string;
  from?: string;
  to?: string;
  page?: number;
  size?: number;
}

export function useAudit(
  clusterId: string,
  filter: AuditFilter = {},
): UseQueryResult<AuditPageView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'audit', filter],
    queryFn: () => {
      const sp = new URLSearchParams();
      for (const [k, v] of Object.entries(filter)) {
        if (v !== undefined && v !== '' && !(k === 'page' && v === 1)) sp.set(k, String(v));
      }
      const qs = sp.toString();
      return request<AuditPageView>(`/clusters/${clusterId}/audit${qs ? `?${qs}` : ''}`);
    },
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

// ── broker events (ADR-0026) ──────────────────────────────────────────────

export interface EventFilter {
  type?: string;
  nodeId?: string;
  address?: string;
  from?: string;
  to?: string;
  page?: number;
  size?: number;
}

export function useEvents(
  clusterId: string,
  filter: EventFilter = {},
): UseQueryResult<BrokerEventPageView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'events', filter],
    queryFn: () => {
      const sp = new URLSearchParams();
      for (const [k, v] of Object.entries(filter)) {
        if (v !== undefined && v !== '' && !(k === 'page' && v === 1)) sp.set(k, String(v));
      }
      const qs = sp.toString();
      return request<BrokerEventPageView>(
        `/clusters/${clusterId}/events${qs ? `?${qs}` : ''}`,
      );
    },
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

export function useDlq(clusterId: string): UseQueryResult<DlqView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'dlq'],
    queryFn: () => request<DlqView>(`/clusters/${clusterId}/dlq`),
    refetchInterval: 10_000,
  });
}

// ── request-reply tracing ──────────────────────────────────────────────────

export function useRrExpectations(
  clusterId: string,
): UseQueryResult<ExpectationView[], ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'rr', 'expectations'],
    queryFn: () => request<ExpectationView[]>(`/clusters/${clusterId}/rr/expectations`),
  });
}

export function useCreateRrExpectation(clusterId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: CreateExpectationRequest) =>
      request<ExpectationView>(`/clusters/${clusterId}/rr/expectations`, {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['clusters', clusterId, 'rr', 'expectations'] }),
  });
}

export function useUpdateRrExpectation(clusterId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }: { id: string; body: UpdateExpectationRequest }) =>
      request<ExpectationView>(`/clusters/${clusterId}/rr/expectations/${id}`, {
        method: 'PUT',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['clusters', clusterId, 'rr', 'expectations'] }),
  });
}

export function useDeleteRrExpectation(clusterId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      request<void>(`/clusters/${clusterId}/rr/expectations/${id}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['clusters', clusterId, 'rr', 'expectations'] }),
  });
}

export interface RrFlowFilter {
  state?: string;
  address?: string;
  correlationId?: string;
  from?: string;
  to?: string;
  page?: number;
  size?: number;
}

export function useRrFlows(
  clusterId: string,
  filter: RrFlowFilter = {},
): UseQueryResult<FlowPageView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'rr', 'flows', filter],
    queryFn: () => {
      const sp = new URLSearchParams();
      for (const [k, v] of Object.entries(filter)) {
        if (v !== undefined && v !== '' && !(k === 'page' && v === 1)) sp.set(k, String(v));
      }
      const qs = sp.toString();
      return request<FlowPageView>(`/clusters/${clusterId}/rr/flows${qs ? `?${qs}` : ''}`);
    },
    refetchInterval: 5_000,
    placeholderData: (prev) => prev,
  });
}

export function useRrFlow(
  clusterId: string,
  flowId: string | undefined,
): UseQueryResult<FlowView, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'rr', 'flows', flowId],
    queryFn: () => request<FlowView>(`/clusters/${clusterId}/rr/flows/${flowId}`),
    enabled: !!flowId,
  });
}

export function useRrStats(
  clusterId: string,
  window = 'PT15M',
): UseQueryResult<StatsResponse, ApiError> {
  return useQuery({
    queryKey: ['clusters', clusterId, 'rr', 'stats', window],
    queryFn: () => request<StatsResponse>(`/clusters/${clusterId}/rr/stats?window=${window}`),
    refetchInterval: 10_000,
  });
}

// ── metrics (metrics spec, ADR-0033) ───────────────────────────────────────

export interface MetricsParams {
  metrics: string[];
  subjectType?: 'CLUSTER' | 'QUEUE';
  subject?: string;
  from: string;
  to: string;
  step?: string;
}

/**
 * `refetchMs` is passed explicitly by the caller rather than defaulting to the
 * global 5s poll every other hook uses — a 7-day chart must not refetch every
 * 5 seconds, and an absolute (non-live) range must never poll at all.
 */
export function useMetrics(
  clusterId: string,
  params: MetricsParams,
  refetchMs: number | false = false,
  enabled = true,
): UseQueryResult<MetricSeriesResponse, ApiError> {
  return useQuery({
    queryKey: keys.metrics(clusterId, params),
    enabled,
    queryFn: () => {
      const sp = new URLSearchParams();
      for (const m of params.metrics) sp.append('metric', m);
      if (params.subjectType) sp.set('subjectType', params.subjectType);
      if (params.subject) sp.set('subject', params.subject);
      sp.set('from', params.from);
      sp.set('to', params.to);
      if (params.step) sp.set('step', params.step);
      return request<MetricSeriesResponse>(`/clusters/${clusterId}/metrics?${sp.toString()}`);
    },
    refetchInterval: refetchMs,
    placeholderData: (prev) => prev,
  });
}

// ── alerting (alerting spec, ADR-0035, ADR-0036) ───────────────────────────

export function useAlertRules(clusterId: string): UseQueryResult<AlertRuleView[], ApiError> {
  return useQuery({
    queryKey: keys.alertRules(clusterId),
    queryFn: () => request<AlertRuleView[]>(`/clusters/${clusterId}/alerts/rules`),
  });
}

export function useCreateAlertRule(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<AlertRuleView, ApiError, AlertRuleRequest>({
    mutationFn: (body) =>
      request<AlertRuleView>(`/clusters/${clusterId}/alerts/rules`, {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.alertRules(clusterId) }),
  });
}

export function useUpdateAlertRule(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<AlertRuleView, ApiError, { ruleId: string; body: AlertRuleRequest }>({
    mutationFn: ({ ruleId, body }) =>
      request<AlertRuleView>(`/clusters/${clusterId}/alerts/rules/${ruleId}`, {
        method: 'PUT',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.alertRules(clusterId) }),
  });
}

export function useDeleteAlertRule(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (ruleId) =>
      request<void>(`/clusters/${clusterId}/alerts/rules/${ruleId}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.alertRules(clusterId) }),
  });
}

export function useFiringAlerts(clusterId: string): UseQueryResult<AlertFiringView[], ApiError> {
  return useQuery({
    queryKey: keys.alertFiring(clusterId),
    queryFn: () => request<AlertFiringView[]>(`/clusters/${clusterId}/alerts/firing`),
    refetchInterval: 15_000,
  });
}

export function useAlertHistory(
  clusterId: string,
  page: number,
  size: number,
): UseQueryResult<AlertFiringPageView, ApiError> {
  return useQuery({
    queryKey: keys.alertHistory(clusterId, page, size),
    queryFn: () =>
      request<AlertFiringPageView>(
        `/clusters/${clusterId}/alerts/history?page=${page}&size=${size}`,
      ),
    placeholderData: (prev) => prev,
  });
}

/** Cross-cluster open-firing counts for the shell badge — polled, since the SSE stream is per-cluster. */
export function useFiringCounts(enabled = true): UseQueryResult<ClusterFiringCountView[], ApiError> {
  return useQuery({
    queryKey: keys.firingCounts,
    queryFn: () => request<ClusterFiringCountView[]>('/alerts/firing'),
    refetchInterval: 30_000,
    enabled,
  });
}

export function useNotificationChannels(): UseQueryResult<NotificationChannelView[], ApiError> {
  return useQuery({
    queryKey: keys.channels,
    queryFn: () => request<NotificationChannelView[]>('/channels'),
  });
}

export function useCreateNotificationChannel() {
  const qc = useQueryClient();
  return useMutation<NotificationChannelView, ApiError, NotificationChannelRequest>({
    mutationFn: (body) =>
      request<NotificationChannelView>('/channels', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.channels }),
  });
}

export function useUpdateNotificationChannel() {
  const qc = useQueryClient();
  return useMutation<
    NotificationChannelView,
    ApiError,
    { channelId: string; body: NotificationChannelRequest }
  >({
    mutationFn: ({ channelId, body }) =>
      request<NotificationChannelView>(`/channels/${channelId}`, {
        method: 'PUT',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.channels }),
  });
}

export function useDeleteNotificationChannel() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (channelId) => request<void>(`/channels/${channelId}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.channels }),
  });
}

export function useTestNotificationChannel() {
  return useMutation<void, ApiError, string>({
    mutationFn: (channelId) =>
      request<void>(`/channels/${channelId}/test`, { method: 'POST' }),
  });
}

export function useRotateCredentials(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<
    void,
    ApiError,
    { username: string; password: string; kind?: 'JOLOKIA_BASIC' | 'CORE' }
  >({
    mutationFn: (body) =>
      request(`/clusters/${clusterId}/credentials`, {
        method: 'PUT',
        body: JSON.stringify(body),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.detail(clusterId) }),
  });
}

// ── identity-and-sessions (ADR-0037) ────────────────────────────────────────

/** `retry: false` — a 401 here means "not logged in," which retrying cannot fix. */
export function useMe(): UseQueryResult<MeView, ApiError> {
  return useQuery({
    queryKey: keys.me,
    queryFn: () => request<MeView>('/auth/me'),
    retry: false,
  });
}

/** Public, unauthenticated — the login screen needs this before any session exists. */
export function useAuthProviders(): UseQueryResult<ProviderView[], ApiError> {
  return useQuery({
    queryKey: keys.authProviders,
    queryFn: () => request<ProviderView[]>('/auth/providers'),
    retry: false,
  });
}

export function useLogin() {
  const qc = useQueryClient();
  return useMutation<MeView, ApiError, LoginRequest>({
    mutationFn: (body) => request<MeView>('/auth/login', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: (me) => qc.setQueryData(keys.me, me),
  });
}

export function useLogout() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, void>({
    mutationFn: () => request<void>('/auth/logout', { method: 'POST' }),
    onSuccess: () => qc.setQueryData(keys.me, undefined),
  });
}

export function useChangePassword() {
  return useMutation<void, ApiError, ChangePasswordRequest>({
    mutationFn: (body) => request<void>('/auth/password', { method: 'POST', body: JSON.stringify(body) }),
  });
}

// ── authorization: users, roles, permissions (ADR-0038) ─────────────────────

export function useUsers(enabled = true): UseQueryResult<UserView[], ApiError> {
  return useQuery({ queryKey: keys.users, queryFn: () => request<UserView[]>('/users'), enabled });
}

export function useCreateUser() {
  const qc = useQueryClient();
  return useMutation<UserView, ApiError, CreateUserRequest>({
    mutationFn: (body) => request<UserView>('/users', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.users }),
  });
}

export function useSetUserDisabled() {
  const qc = useQueryClient();
  return useMutation<UserView, ApiError, { userId: string; disabled: boolean }>({
    mutationFn: ({ userId, disabled }) =>
      request<UserView>(`/users/${userId}/disabled`, {
        method: 'PUT',
        body: JSON.stringify({ disabled } satisfies SetDisabledRequest),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.users }),
  });
}

export function useAddGrant() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, { userId: string; body: GrantRequest }>({
    mutationFn: ({ userId, body }) =>
      request<void>(`/users/${userId}/grants`, { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.users }),
  });
}

export function useRemoveGrant() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, { userId: string; roleId: string; scopeType: string; scopeId?: string }>({
    mutationFn: ({ userId, roleId, scopeType, scopeId }) => {
      const qs = new URLSearchParams({ scopeType, ...(scopeId ? { scopeId } : {}) });
      return request<void>(`/users/${userId}/grants/${roleId}?${qs}`, { method: 'DELETE' });
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.users }),
  });
}

export function useRoles(): UseQueryResult<RoleView[], ApiError> {
  return useQuery({ queryKey: keys.roles, queryFn: () => request<RoleView[]>('/roles') });
}

export function usePermissionsCatalogue(): UseQueryResult<PermissionView[], ApiError> {
  return useQuery({ queryKey: keys.permissions, queryFn: () => request<PermissionView[]>('/permissions') });
}

export function useCreateRole() {
  const qc = useQueryClient();
  return useMutation<RoleView, ApiError, RoleRequest>({
    mutationFn: (body) => request<RoleView>('/roles', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.roles }),
  });
}

export function useUpdateRole() {
  const qc = useQueryClient();
  return useMutation<RoleView, ApiError, { roleId: string; body: RoleRequest }>({
    mutationFn: ({ roleId, body }) =>
      request<RoleView>(`/roles/${roleId}`, { method: 'PUT', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.roles }),
  });
}

export function useDeleteRole() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (roleId) => request<void>(`/roles/${roleId}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.roles }),
  });
}

// ── environments ─────────────────────────────────────────────────────────────

export function useEnvironments(): UseQueryResult<EnvironmentView[], ApiError> {
  return useQuery({ queryKey: keys.environments, queryFn: () => request<EnvironmentView[]>('/environments') });
}

export function useCreateEnvironment() {
  const qc = useQueryClient();
  return useMutation<EnvironmentView, ApiError, EnvironmentRequest>({
    mutationFn: (body) => request<EnvironmentView>('/environments', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.environments }),
  });
}

export function useUpdateEnvironment() {
  const qc = useQueryClient();
  return useMutation<EnvironmentView, ApiError, { environmentId: string; body: EnvironmentRequest }>({
    mutationFn: ({ environmentId, body }) =>
      request<EnvironmentView>(`/environments/${environmentId}`, { method: 'PUT', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.environments }),
  });
}

export function useDeleteEnvironment() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (environmentId) => request<void>(`/environments/${environmentId}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.environments }),
  });
}

export function useAssignClusterEnvironment(clusterId: string) {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string | null>({
    mutationFn: (environmentId) =>
      request<void>(`/clusters/${clusterId}/environment`, {
        method: 'PUT',
        body: JSON.stringify({ environmentId }),
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.all }),
  });
}

// ── API tokens ───────────────────────────────────────────────────────────────

export function useTokens(): UseQueryResult<TokenView[], ApiError> {
  return useQuery({ queryKey: keys.tokens, queryFn: () => request<TokenView[]>('/tokens') });
}

export function useCreateToken() {
  const qc = useQueryClient();
  return useMutation<CreatedTokenView, ApiError, CreateTokenRequest>({
    mutationFn: (body) => request<CreatedTokenView>('/tokens', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.tokens }),
  });
}

export function useRevokeToken() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (tokenId) => request<void>(`/tokens/${tokenId}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.tokens }),
  });
}

// ── OIDC role mappings (oidc-sso spec) ──────────────────────────────────────

export function useOidcMappings(): UseQueryResult<OidcMappingView[], ApiError> {
  return useQuery({ queryKey: keys.oidcMappings, queryFn: () => request<OidcMappingView[]>('/oidc/mappings') });
}

export function useCreateOidcMapping() {
  const qc = useQueryClient();
  return useMutation<OidcMappingView, ApiError, OidcMappingRequest>({
    mutationFn: (body) =>
      request<OidcMappingView>('/oidc/mappings', { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.oidcMappings }),
  });
}

export function useDeleteOidcMapping() {
  const qc = useQueryClient();
  return useMutation<void, ApiError, string>({
    mutationFn: (mappingId) => request<void>(`/oidc/mappings/${mappingId}`, { method: 'DELETE' }),
    onSuccess: () => qc.invalidateQueries({ queryKey: keys.oidcMappings }),
  });
}
