/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put"];
        post?: never;
        delete: operations["reset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rotateCredentials"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rediscover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rediscover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues/{queueName}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["browse"];
        put?: never;
        post: operations["send"];
        delete: operations["purge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues/{queueName}/messages/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["overrideNode"];
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["topology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues/{queueName}/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/producers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["producers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/consumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consumers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["connections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["addresses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateSettingRequest: {
            value: string;
        };
        RotateCredentialsRequest: {
            username: string;
            password: string;
        };
        Credentials: {
            username: string;
            password: string;
        };
        RegisterClusterRequest: {
            seedUrls: string[];
            name?: string;
            description?: string;
            credentials?: components["schemas"]["Credentials"];
            tlsBundle?: string;
        };
        CapabilitiesView: {
            managementRead: components["schemas"]["CapabilityView"];
            managementWrite: components["schemas"]["CapabilityView"];
            notifications: components["schemas"]["CapabilityView"];
            messageIo: components["schemas"]["CapabilityView"];
        };
        CapabilityView: {
            status: string;
            reason: string;
            brokerXmlSnippet?: string | null;
        };
        RegisterPreview: {
            capabilities: components["schemas"]["CapabilitiesView"];
            /** Format: int32 */
            reachableSeeds: number;
            /** Format: int32 */
            discoveredNodes: number;
            nodeNames: string[];
        };
        ClusterDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            topology: components["schemas"]["TopologyView"];
            capabilities: components["schemas"]["CapabilitiesView"];
            health: components["schemas"]["HealthView"];
        };
        HealthView: {
            /** Format: uuid */
            clusterId: string;
            level: string;
            liveEndpointNames: string[];
            splitBrain: string;
            replicationBehind: boolean;
            notes: string[];
        };
        LogicalNodeView: {
            artemisNodeId?: string | null;
            splitBrain: string;
            replicationBehind: boolean;
            endpoints: components["schemas"]["NodeEndpointView"][];
        };
        NodeEndpointView: {
            /** Format: uuid */
            id: string;
            name: string;
            artemisNodeId?: string | null;
            jolokiaUrl?: string | null;
            coreUrl?: string | null;
            haRole: string;
            state: string;
            active: boolean;
            replicaSync?: boolean | null;
            version?: string | null;
            lastError?: string | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            discovered: boolean;
            manualOverride: boolean;
            manageable: boolean;
        };
        TopologyView: {
            /** Format: uuid */
            clusterId: string;
            nodes: components["schemas"]["LogicalNodeView"][];
        };
        SendMessageRequest: {
            /** Format: int32 */
            type: number;
            durable?: boolean;
            body?: string;
            headers?: {
                [key: string]: unknown;
            };
            properties?: {
                [key: string]: unknown;
            };
        };
        AffectedView: {
            /** Format: int64 */
            affectedCount: number;
            dryRun: boolean;
            /** Format: uuid */
            node: string;
        };
        DryRunView: {
            /** Format: int64 */
            affectedCount: number;
            /** Format: int64 */
            cap: number;
            overCap: boolean;
            /** Format: uuid */
            node: string;
        };
        MessageActionRequest: {
            messageIds?: number[];
            filter?: string;
            targetQueue?: string;
        };
        NodeOverrideRequest: {
            jolokiaUrl: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        SettingValue: {
            value: string;
            overridden: boolean;
            defaultValue: string;
        };
        SettingsResponse: {
            settings: {
                [key: string]: components["schemas"]["SettingValue"];
            };
        };
        ClusterSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** @enum {string} */
            health: "OK" | "DEGRADED" | "CRITICAL" | "UNKNOWN";
            /** Format: int32 */
            nodeCount: number;
            /** Format: date-time */
            updatedAt: string;
        };
        ResourceQuery: {
            q?: string;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string;
        };
        PagedViewSessionView: {
            data: components["schemas"]["SessionView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        SessionView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            sessionId?: string | null;
            user?: string | null;
            connectionId?: string | null;
            /** Format: int64 */
            consumerCount: number;
            /** Format: int64 */
            producerCount: number;
            creationTime?: string | null;
        };
        PagedViewQueueView: {
            data: components["schemas"]["QueueView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        QueueNodeCell: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            stale: boolean;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: int64 */
            messageCount: number;
            /** Format: int64 */
            consumerCount: number;
            /** Format: int64 */
            deliveringCount: number;
            /** Format: int64 */
            scheduledCount: number;
        };
        QueueView: {
            address: string;
            queueName: string;
            routingType: string;
            durable: boolean;
            /** Format: int64 */
            totalMessageCount: number;
            /** Format: int64 */
            totalConsumerCount: number;
            /** Format: int64 */
            totalDeliveringCount: number;
            /** Format: int64 */
            totalScheduledCount: number;
            /** Format: int32 */
            nodesPresent: number;
            /** Format: int32 */
            nodesTotal: number;
            perNode: components["schemas"]["QueueNodeCell"][];
        };
        MessagePageView: {
            data: components["schemas"]["MessageSummaryView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: uuid */
            node: string;
        };
        MessageSummaryView: {
            /** Format: int64 */
            messageId: number;
            /** Format: int32 */
            type: number;
            durable: boolean;
            /** Format: int32 */
            priority: number;
            /** Format: int64 */
            timestamp: number;
            /** Format: int64 */
            expiration: number;
            /** Format: int64 */
            size: number;
            groupId?: string | null;
            correlationId?: string | null;
            bodyPreview?: string | null;
            bodyTruncated: boolean;
            /** Format: int32 */
            propertyCount: number;
        };
        MessageDetailView: {
            /** Format: int64 */
            messageId: number;
            /** Format: int32 */
            type: number;
            durable: boolean;
            /** Format: int32 */
            priority: number;
            /** Format: int64 */
            timestamp: number;
            /** Format: int64 */
            expiration: number;
            /** Format: int64 */
            size: number;
            groupId?: string | null;
            correlationId?: string | null;
            userId?: string | null;
            body?: string | null;
            bodyTruncated: boolean;
            /** Format: int32 */
            observedLimitBytes?: number | null;
            /** Format: uuid */
            node: string;
            stringProperties: {
                [key: string]: string;
            };
            intProperties: {
                [key: string]: number;
            };
            longProperties: {
                [key: string]: number;
            };
            doubleProperties: {
                [key: string]: number;
            };
            booleanProperties: {
                [key: string]: boolean;
            };
        };
        PagedViewProducerView: {
            data: components["schemas"]["ProducerView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        ProducerView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            producerId?: string | null;
            name?: string | null;
            sessionId?: string | null;
            address?: string | null;
            protocol?: string | null;
            /** Format: int64 */
            messagesSent: number;
        };
        DlqAddress: {
            address: string;
            kind: string;
            queues: components["schemas"]["DlqQueue"][];
        };
        DlqQueue: {
            queueName: string;
            address: string;
            /** Format: int64 */
            totalDepth: number;
            perNode: components["schemas"]["DlqQueueDepth"][];
        };
        DlqQueueDepth: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            /** Format: int64 */
            depth: number;
        };
        DlqView: {
            addresses: components["schemas"]["DlqAddress"][];
            settingsAvailable: boolean;
        };
        ConsumerView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            consumerId?: string | null;
            sessionId?: string | null;
            queueName?: string | null;
            address?: string | null;
            protocol?: string | null;
            /** Format: int64 */
            messagesDelivered: number;
            /** Format: int64 */
            messagesAcknowledged: number;
            status?: string | null;
        };
        PagedViewConsumerView: {
            data: components["schemas"]["ConsumerView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        ConnectionView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            connectionId?: string | null;
            remoteAddress?: string | null;
            protocol?: string | null;
            clientId?: string | null;
            /** Format: int64 */
            sessionCount: number;
            creationTime?: string | null;
        };
        PagedViewConnectionView: {
            data: components["schemas"]["ConnectionView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        AuditEventView: {
            /** Format: date-time */
            ts: string;
            username?: string | null;
            sourceIp?: string | null;
            requestId?: string | null;
            action: string;
            targetType?: string | null;
            targetName?: string | null;
            /** Format: int64 */
            affectedCount?: number | null;
            outcome: string;
            dryRun: boolean;
            params?: string | null;
            error?: string | null;
            /** Format: uuid */
            nodeId?: string | null;
        };
        AuditPageView: {
            data: components["schemas"]["AuditEventView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        AddressView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            name: string;
            routingTypes?: string | null;
            /** Format: int64 */
            queueCount: number;
            /** Format: int64 */
            messageCount: number;
        };
        PagedViewAddressView: {
            data: components["schemas"]["AddressView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateCredentialsRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterSummary"][];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterClusterRequest"];
            };
        };
        responses: {
            /** @description dryRun=true: connection probe result, nothing persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterPreview"];
                };
            };
            /** @description cluster registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterDetail"];
                };
            };
        };
    };
    rediscover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopologyView"];
                };
            };
        };
    };
    browse: {
        parameters: {
            query?: {
                node?: string;
                filter?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessagePageView"];
                };
            };
        };
    };
    send: {
        parameters: {
            query?: {
                node?: string;
                dryRun?: boolean;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AffectedView"] | components["schemas"]["DryRunView"];
                };
            };
        };
    };
    purge: {
        parameters: {
            query?: {
                node?: string;
                dryRun?: boolean;
                override?: boolean;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AffectedView"] | components["schemas"]["DryRunView"];
                };
            };
        };
    };
    action: {
        parameters: {
            query?: {
                node?: string;
                dryRun?: boolean;
                override?: boolean;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AffectedView"] | components["schemas"]["DryRunView"];
                };
            };
        };
    };
    overrideNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeOverrideRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeEndpointView"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query: {
                clusterId: string;
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterDetail"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    topology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopologyView"];
                };
            };
        };
    };
    sessions: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewSessionView"];
                };
            };
        };
    };
    queues: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewQueueView"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: {
                node?: string;
                filter?: string;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
                messageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageDetailView"];
                };
            };
        };
    };
    producers: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewProducerView"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthView"];
                };
            };
        };
    };
    view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DlqView"];
                };
            };
        };
    };
    consumers: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewConsumerView"];
                };
            };
        };
    };
    connections: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewConnectionView"];
                };
            };
        };
    };
    capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapabilitiesView"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                user?: string;
                action?: string;
                outcome?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditPageView"];
                };
            };
        };
    };
    addresses: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewAddressView"];
                };
            };
        };
    };
}
