/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{userId}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setDisabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put"];
        post?: never;
        delete: operations["reset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/{environmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rr/expectations/{expectationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateExpectation"];
        post?: never;
        delete: operations["deleteExpectation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assign"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rotateCredentials"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/alerts/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRule"];
        post?: never;
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oidc/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rr/expectations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExpectations"];
        put?: never;
        post: operations["createExpectation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rediscover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rediscover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues/{queueName}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["browse"];
        put?: never;
        post: operations["send"];
        delete: operations["purge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues/{queueName}/messages/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rules"];
        put?: never;
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/{channelId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["overrideNode"];
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["topology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rr/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rr/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["flows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/rr/flows/{flowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["flow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/queues/{queueName}/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/producers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["producers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/consumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consumers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["connections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/alerts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/alerts/firing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["firing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["addresses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/firing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["firing_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/grants/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oidc/mappings/{mappingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetDisabledRequest: {
            disabled?: boolean;
        };
        GrantSummary: {
            roleName: string;
            /** Format: uuid */
            roleId: string;
            scopeType: string;
            /** Format: uuid */
            scopeId?: string | null;
        };
        UserView: {
            /** Format: uuid */
            id: string;
            username: string;
            email?: string | null;
            authSource: string;
            disabled: boolean;
            mustChangePassword: boolean;
            grants: components["schemas"]["GrantSummary"][];
        };
        UpdateSettingRequest: {
            value: string;
        };
        RoleRequest: {
            name: string;
            permissions: string[];
        };
        RoleView: {
            /** Format: uuid */
            id: string;
            name: string;
            builtin: boolean;
            permissions: string[];
        };
        EnvironmentRequest: {
            name: string;
            colour?: string | null;
            /** Format: int32 */
            sortOrder: number;
        };
        EnvironmentView: {
            /** Format: uuid */
            id: string;
            name: string;
            colour?: string | null;
            /** Format: int32 */
            sortOrder: number;
        };
        UpdateExpectationRequest: {
            replyAddress?: string;
            correlationProperty?: string;
            /** Format: int32 */
            deadlineMs?: number;
            /** Format: int32 */
            samplePerMin?: number;
            capturePayload?: boolean;
            enabled?: boolean;
        };
        ExpectationView: {
            /** Format: uuid */
            id: string;
            requestAddress: string;
            replyAddress?: string | null;
            correlationProperty?: string | null;
            /** Format: int32 */
            deadlineMs?: number | null;
            /** Format: int32 */
            samplePerMin: number;
            capturePayload: boolean;
            enabled: boolean;
        };
        AssignEnvironmentRequest: {
            /** Format: uuid */
            environmentId?: string;
        };
        RotateCredentialsRequest: {
            username: string;
            password: string;
            kind?: string;
        };
        AlertRuleRequest: {
            name: string;
            kind: string;
            metric?: string;
            comparator?: string;
            /** Format: double */
            threshold?: number;
            stateCondition?: string;
            /** Format: int32 */
            forSeconds?: number;
            severity: string;
            scope?: string;
            enabled?: boolean;
            channelIds?: string[];
        };
        AlertRuleView: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clusterId: string;
            name: string;
            kind: string;
            metric?: string | null;
            comparator?: string | null;
            /** Format: double */
            threshold?: number | null;
            stateCondition?: string | null;
            /** Format: int32 */
            forSeconds: number;
            severity: string;
            scope?: string | null;
            enabled: boolean;
            channelIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NotificationChannelRequest: {
            name: string;
            kind: string;
            config?: string;
            secret?: string;
            enabled?: boolean;
        };
        NotificationChannelView: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: string;
            config: string;
            enabled: boolean;
            hasSecret: boolean;
        };
        CreateUserRequest: {
            username: string;
            email?: string;
            password: string;
        };
        GrantRequest: {
            /** Format: uuid */
            roleId: string;
            scopeType: string;
            /** Format: uuid */
            scopeId?: string | null;
        };
        CreateTokenRequest: {
            name: string;
            /** Format: date-time */
            expiresAt?: string | null;
            grants: components["schemas"]["TokenGrantRequest"][];
        };
        TokenGrantRequest: {
            action: string;
            scopeType: string;
            /** Format: uuid */
            scopeId?: string | null;
        };
        CreatedTokenView: {
            token: components["schemas"]["TokenView"];
            value: string;
        };
        TokenView: {
            /** Format: uuid */
            id: string;
            name: string;
            prefix: string;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        OidcMappingRequest: {
            claim: string;
            claimValue: string;
            /** Format: uuid */
            roleId: string;
            scopeType: string;
            /** Format: uuid */
            scopeId?: string | null;
        };
        OidcMappingView: {
            /** Format: uuid */
            id: string;
            claim: string;
            claimValue: string;
            /** Format: uuid */
            roleId: string;
            roleName: string;
            scopeType: string;
            /** Format: uuid */
            scopeId?: string | null;
        };
        Credentials: {
            username: string;
            password: string;
        };
        RegisterClusterRequest: {
            seedUrls: string[];
            name?: string;
            description?: string;
            credentials?: components["schemas"]["Credentials"];
            coreCredentials?: components["schemas"]["Credentials"];
            tlsBundle?: string;
        };
        CapabilitiesView: {
            managementRead: components["schemas"]["CapabilityView"];
            managementWrite: components["schemas"]["CapabilityView"];
            notifications: components["schemas"]["CapabilityView"];
            messageIo: components["schemas"]["CapabilityView"];
            slowConsumerDetection: components["schemas"]["CapabilityView"];
        };
        CapabilityView: {
            status: string;
            reason: string;
            brokerXmlSnippet?: string | null;
        };
        LogicalNodeView: {
            artemisNodeId?: string | null;
            splitBrain: string;
            replicationBehind: boolean;
            endpoints: components["schemas"]["NodeEndpointView"][];
        };
        NodeEndpointView: {
            /** Format: uuid */
            id: string;
            name: string;
            artemisNodeId?: string | null;
            jolokiaUrl?: string | null;
            coreUrl?: string | null;
            haRole: string;
            state: string;
            active: boolean;
            replicaSync?: boolean | null;
            version?: string | null;
            lastError?: string | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            discovered: boolean;
            manualOverride: boolean;
            manageable: boolean;
        };
        RegisterPreview: {
            capabilities: components["schemas"]["CapabilitiesView"];
            /** Format: int32 */
            reachableSeeds: number;
            /** Format: int32 */
            discoveredNodes: number;
            topology: components["schemas"]["TopologyView"];
        };
        TopologyView: {
            /** Format: uuid */
            clusterId: string;
            nodes: components["schemas"]["LogicalNodeView"][];
        };
        ClusterDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            topology: components["schemas"]["TopologyView"];
            capabilities: components["schemas"]["CapabilitiesView"];
            health: components["schemas"]["HealthView"];
            /** Format: uuid */
            environmentId?: string | null;
        };
        HealthView: {
            /** Format: uuid */
            clusterId: string;
            level: string;
            liveEndpointNames: string[];
            splitBrain: string;
            replicationBehind: boolean;
            notes: string[];
        };
        CreateExpectationRequest: {
            requestAddress: string;
            replyAddress?: string;
            correlationProperty?: string;
            /** Format: int32 */
            deadlineMs?: number;
            /** Format: int32 */
            samplePerMin?: number;
            capturePayload?: boolean;
        };
        SendMessageRequest: {
            /** Format: int32 */
            type: number;
            durable?: boolean;
            body?: string;
            bodyBase64?: boolean;
            headers?: {
                [key: string]: unknown;
            };
            properties?: {
                [key: string]: unknown;
            };
        };
        AffectedView: {
            /** Format: int64 */
            affectedCount: number;
            dryRun: boolean;
            /** Format: uuid */
            node: string;
        };
        DryRunView: {
            /** Format: int64 */
            affectedCount: number;
            /** Format: int64 */
            cap: number;
            overCap: boolean;
            /** Format: uuid */
            node: string;
        };
        MessageActionRequest: {
            messageIds?: number[];
            filter?: string;
            targetQueue?: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        GrantView: {
            scopeType: string;
            /** Format: uuid */
            scopeId?: string | null;
            permissions: string[];
        };
        MeView: {
            /** Format: uuid */
            id: string;
            username: string;
            mustChangePassword: boolean;
            grants: components["schemas"]["GrantView"][];
        };
        NodeOverrideRequest: {
            jolokiaUrl?: string;
            coreUrl?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        SettingValue: {
            value: string;
            overridden: boolean;
            defaultValue: string;
        };
        SettingsResponse: {
            settings: {
                [key: string]: components["schemas"]["SettingValue"];
            };
        };
        PermissionView: {
            action: string;
            label: string;
        };
        ClusterSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** @enum {string} */
            health: "OK" | "DEGRADED" | "CRITICAL" | "UNKNOWN";
            /** Format: int32 */
            nodeCount: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uuid */
            environmentId?: string | null;
        };
        ResourceQuery: {
            q?: string;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string;
        };
        PagedViewSessionView: {
            data: components["schemas"]["SessionView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        SessionView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            sessionId?: string | null;
            user?: string | null;
            connectionId?: string | null;
            /** Format: int64 */
            consumerCount: number;
            /** Format: int64 */
            producerCount: number;
            creationTime?: string | null;
        };
        AddressStatsView: {
            address: string;
            /** Format: int64 */
            inFlight: number;
            /** Format: int64 */
            oldestInFlightMs?: number | null;
            /** Format: int64 */
            completed: number;
            /** Format: int64 */
            timedOut: number;
            /** Format: int64 */
            orphaned: number;
            /** Format: int64 */
            responderDropped: number;
            /** Format: double */
            p50Ms?: number | null;
            /** Format: double */
            p95Ms?: number | null;
            /** Format: double */
            p99Ms?: number | null;
            sampled: boolean;
            /** Format: double */
            coverageRatio?: number | null;
            /** Format: int64 */
            windowMs: number;
        };
        StatsResponse: {
            addresses: components["schemas"]["AddressStatsView"][];
        };
        FlowPageView: {
            data: components["schemas"]["FlowView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        FlowView: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clusterId: string;
            /** Format: uuid */
            nodeId?: string | null;
            requestAddress?: string | null;
            replyDestination?: string | null;
            replyKind: string;
            state: string;
            correlationId?: string | null;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            deadlineAt?: string | null;
            /** Format: date-time */
            repliedAt?: string | null;
            /** Format: int64 */
            latencyMs?: number | null;
            events?: components["schemas"]["RrEventView"][] | null;
        };
        RrEventView: {
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            ts: string;
            kind: string;
            /** Format: uuid */
            nodeId?: string | null;
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        PagedViewQueueView: {
            data: components["schemas"]["QueueView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        QueueNodeCell: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            stale: boolean;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: int64 */
            messageCount: number;
            /** Format: int64 */
            consumerCount: number;
            /** Format: int64 */
            deliveringCount: number;
            /** Format: int64 */
            scheduledCount: number;
        };
        QueueView: {
            address: string;
            queueName: string;
            routingType: string;
            durable: boolean;
            /** Format: int64 */
            totalMessageCount: number;
            /** Format: int64 */
            totalConsumerCount: number;
            /** Format: int64 */
            totalDeliveringCount: number;
            /** Format: int64 */
            totalScheduledCount: number;
            /** Format: int32 */
            nodesPresent: number;
            /** Format: int32 */
            nodesTotal: number;
            perNode: components["schemas"]["QueueNodeCell"][];
        };
        MessagePageView: {
            data: components["schemas"]["MessageSummaryView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: uuid */
            node: string;
            transport: string;
        };
        MessageSummaryView: {
            /** Format: int64 */
            messageId: number;
            /** Format: int32 */
            type: number;
            durable: boolean;
            /** Format: int32 */
            priority: number;
            /** Format: int64 */
            timestamp: number;
            /** Format: int64 */
            expiration: number;
            /** Format: int64 */
            size: number;
            groupId?: string | null;
            correlationId?: string | null;
            bodyPreview?: string | null;
            bodyTruncated: boolean;
            /** Format: int32 */
            propertyCount: number;
        };
        MessageDetailView: {
            /** Format: int64 */
            messageId: number;
            /** Format: int32 */
            type: number;
            durable: boolean;
            /** Format: int32 */
            priority: number;
            /** Format: int64 */
            timestamp: number;
            /** Format: int64 */
            expiration: number;
            /** Format: int64 */
            size: number;
            groupId?: string | null;
            correlationId?: string | null;
            userId?: string | null;
            body?: string | null;
            bodyEncoding: string;
            contentType?: string | null;
            bodyTruncated: boolean;
            /** Format: int32 */
            observedLimitBytes?: number | null;
            transport: string;
            /** Format: uuid */
            node: string;
            stringProperties: {
                [key: string]: string;
            };
            intProperties: {
                [key: string]: number;
            };
            longProperties: {
                [key: string]: number;
            };
            doubleProperties: {
                [key: string]: number;
            };
            booleanProperties: {
                [key: string]: boolean;
            };
        };
        PagedViewProducerView: {
            data: components["schemas"]["ProducerView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        ProducerView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            producerId?: string | null;
            name?: string | null;
            sessionId?: string | null;
            address?: string | null;
            protocol?: string | null;
            /** Format: int64 */
            messagesSent: number;
        };
        MetricPoint: {
            /** Format: date-time */
            ts: string;
            /** Format: double */
            value: number;
            /** Format: double */
            peak?: number | null;
        };
        MetricSeries: {
            metric: string;
            kind: string;
            unit: string;
            points: components["schemas"]["MetricPoint"][];
        };
        MetricSeriesResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            step: string;
            truncated: boolean;
            series: components["schemas"]["MetricSeries"][];
        };
        BrokerEventPageView: {
            data: components["schemas"]["BrokerEventView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            dropped: number;
            /** Format: date-time */
            oldestRetained?: string | null;
        };
        BrokerEventView: {
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            receivedAt: string;
            type: string;
            address?: string | null;
            routingName?: string | null;
            consumerName?: string | null;
            sessionName?: string | null;
            connectionName?: string | null;
            remoteAddress?: string | null;
            username?: string | null;
            /** Format: uuid */
            nodeId?: string | null;
            props?: {
                [key: string]: unknown;
            } | null;
        };
        DlqAddress: {
            address: string;
            kind: string;
            queues: components["schemas"]["DlqQueue"][];
        };
        DlqQueue: {
            queueName: string;
            address: string;
            /** Format: int64 */
            totalDepth: number;
            perNode: components["schemas"]["DlqQueueDepth"][];
        };
        DlqQueueDepth: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            /** Format: int64 */
            depth: number;
        };
        DlqView: {
            addresses: components["schemas"]["DlqAddress"][];
            settingsAvailable: boolean;
        };
        ConsumerView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            consumerId?: string | null;
            sessionId?: string | null;
            queueName?: string | null;
            address?: string | null;
            protocol?: string | null;
            /** Format: int64 */
            messagesDelivered: number;
            /** Format: int64 */
            messagesAcknowledged: number;
            status?: string | null;
        };
        PagedViewConsumerView: {
            data: components["schemas"]["ConsumerView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        ConnectionView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            connectionId?: string | null;
            remoteAddress?: string | null;
            protocol?: string | null;
            clientId?: string | null;
            /** Format: int64 */
            sessionCount: number;
            creationTime?: string | null;
        };
        PagedViewConnectionView: {
            data: components["schemas"]["ConnectionView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        AuditEventView: {
            /** Format: date-time */
            ts: string;
            username?: string | null;
            sourceIp?: string | null;
            requestId?: string | null;
            action: string;
            targetType?: string | null;
            targetName?: string | null;
            /** Format: int64 */
            affectedCount?: number | null;
            outcome: string;
            dryRun: boolean;
            params?: string | null;
            error?: string | null;
            /** Format: uuid */
            nodeId?: string | null;
        };
        AuditPageView: {
            data: components["schemas"]["AuditEventView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        AlertFiringPageView: {
            items: components["schemas"]["AlertFiringView"][];
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
        };
        AlertFiringView: {
            /** Format: int64 */
            seq: number;
            /** Format: uuid */
            ruleId: string;
            ruleName: string;
            subjectKey: string;
            severity: string;
            /** Format: double */
            value?: number | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        AddressView: {
            /** Format: uuid */
            nodeId: string;
            nodeName: string;
            name: string;
            routingTypes?: string | null;
            /** Format: int64 */
            queueCount: number;
            /** Format: int64 */
            messageCount: number;
        };
        PagedViewAddressView: {
            data: components["schemas"]["AddressView"][];
            /** Format: int64 */
            count: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        ProviderView: {
            registrationId: string;
            label: string;
            authorizationUrl: string;
        };
        ClusterFiringCountView: {
            /** Format: uuid */
            clusterId: string;
            /** Format: int64 */
            firing: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setDisabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDisabledRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserView"];
                };
            };
        };
    };
    put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleView"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvironmentView"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateExpectation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                expectationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpectationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpectationView"];
                };
            };
        };
    };
    deleteExpectation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                expectationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignEnvironmentRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateCredentialsRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertRuleView"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationChannelView"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserView"];
                };
            };
        };
    };
    addGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenView"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedTokenView"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleView"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoleView"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OidcMappingView"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OidcMappingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OidcMappingView"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvironmentView"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvironmentView"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterSummary"][];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterClusterRequest"];
            };
        };
        responses: {
            /** @description dryRun=true: connection probe result, nothing persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterPreview"];
                };
            };
            /** @description cluster registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterDetail"];
                };
            };
        };
    };
    listExpectations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpectationView"][];
                };
            };
        };
    };
    createExpectation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpectationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpectationView"];
                };
            };
        };
    };
    rediscover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopologyView"];
                };
            };
        };
    };
    browse: {
        parameters: {
            query?: {
                node?: string;
                filter?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessagePageView"];
                };
            };
        };
    };
    send: {
        parameters: {
            query?: {
                node?: string;
                dryRun?: boolean;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AffectedView"] | components["schemas"]["DryRunView"];
                };
            };
        };
    };
    purge: {
        parameters: {
            query?: {
                node?: string;
                dryRun?: boolean;
                override?: boolean;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AffectedView"] | components["schemas"]["DryRunView"];
                };
            };
        };
    };
    action: {
        parameters: {
            query?: {
                node?: string;
                dryRun?: boolean;
                override?: boolean;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AffectedView"] | components["schemas"]["DryRunView"];
                };
            };
        };
    };
    rules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertRuleView"][];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertRuleView"];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationChannelView"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationChannelView"];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeView"];
                };
            };
        };
    };
    overrideNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeOverrideRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeEndpointView"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query: {
                clusterId: string;
                topics?: string;
            };
            header?: {
                "Last-Event-ID"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    list_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PermissionView"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterDetail"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    topology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopologyView"];
                };
            };
        };
    };
    sessions: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewSessionView"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    flows: {
        parameters: {
            query?: {
                state?: string;
                address?: string;
                correlationId?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FlowPageView"];
                };
            };
        };
    };
    flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
                flowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FlowView"];
                };
            };
        };
    };
    queues: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewQueueView"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: {
                node?: string;
                filter?: string;
            };
            header?: never;
            path: {
                clusterId: string;
                queueName: string;
                messageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageDetailView"];
                };
            };
        };
    };
    producers: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewProducerView"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query: {
                metric: string[];
                subjectType?: string;
                subject?: string;
                from?: string;
                to?: string;
                step?: string;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetricSeriesResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthView"];
                };
            };
        };
    };
    list_8: {
        parameters: {
            query?: {
                type?: string;
                nodeId?: string;
                address?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BrokerEventPageView"];
                };
            };
        };
    };
    view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DlqView"];
                };
            };
        };
    };
    consumers: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewConsumerView"];
                };
            };
        };
    };
    connections: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewConnectionView"];
                };
            };
        };
    };
    capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapabilitiesView"];
                };
            };
        };
    };
    list_9: {
        parameters: {
            query?: {
                user?: string;
                action?: string;
                outcome?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditPageView"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertFiringPageView"];
                };
            };
        };
    };
    firing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlertFiringView"][];
                };
            };
        };
    };
    addresses: {
        parameters: {
            query: {
                query: components["schemas"]["ResourceQuery"];
            };
            header?: never;
            path: {
                clusterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedViewAddressView"];
                };
            };
        };
    };
    providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProviderView"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeView"];
                };
            };
        };
    };
    firing_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterFiringCountView"][];
                };
            };
        };
    };
    removeGrant: {
        parameters: {
            query: {
                scopeType: string;
                scopeId?: string;
            };
            header?: never;
            path: {
                userId: string;
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mappingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
