/**
 * Transport to the Artemis Studio API: `request<T>()` and the RFC 9457 `ApiError`.
 *
 * DTO types come from `schema.d.ts`, generated by `openapi-typescript` from the
 * backend's committed OpenAPI snapshot (`web/openapi.json`) — ADR-0019. Each
 * feature's `api.ts` names the DTOs it uses and holds its own hooks and query
 * keys, every cluster-scoped key under {@link clusterKey}.
 */
export const BASE = '/api/v1';

/** A parsed `application/problem+json` body. */
export class ApiError extends Error {
  readonly status: number;
  readonly type: string;
  readonly title: string;
  readonly brokerErrorKind?: string;
  readonly fieldErrors: { field: string; message: string }[];
  /**
   * The whole `problem+json` body. Handlers attach extra properties to a problem
   * — the offending token on a syntax error, the estimate and ceiling on a
   * refused query — and a message with the number left out is not something an
   * operator can act on.
   */
  readonly problem: Record<string, unknown>;

  constructor(status: number, body: Record<string, unknown>) {
    super((body.detail as string) ?? (body.title as string) ?? `Request failed (${status})`);
    this.name = 'ApiError';
    this.status = status;
    this.type = (body.type as string) ?? 'about:blank';
    this.title = (body.title as string) ?? 'Error';
    this.brokerErrorKind = body.brokerErrorKind as string | undefined;
    this.fieldErrors = (body.errors as { field: string; message: string }[] | undefined) ?? [];
    this.problem = body;
  }
}

/** What the server says about an operation it held for approval instead of running. */
export interface HeldOperation {
  id: string;
  /** What the operation would do, in words, such as `Purge queue "orders" on prod`. */
  summary: string;
  /** When the request lapses unless someone decides it, as an ISO instant. */
  expiresAt: string;
  /** The held operation's API path. */
  link: string;
}

/** The header a `202` carries when the operation was held for approval rather than run. */
export const HELD_HEADER = 'X-Studio-Held-Operation';

/**
 * The operation was not run but held for a second person to approve. It is thrown, not returned, so a
 * mutation's success path (its toast, its invalidation, the dialog closing on "done") never treats a held
 * operation as done; `notify.settle` and `ErrorState` show it as sent for approval, not as a failure.
 */
export class OperationHeldError extends Error {
  readonly heldOperation: HeldOperation;

  constructor(heldOperation: HeldOperation) {
    super(`Sent for approval: ${heldOperation.summary}`);
    this.name = 'OperationHeldError';
    this.heldOperation = heldOperation;
  }
}

/** The root every held-operation query key starts from, so a held outcome or a `held` signal refreshes all of them. */
export const heldOperationsKey = ['held-operations'] as const;

/** Reads a held response's body; the header's id wins, so a body that lost it still names the request. */
function heldOperationOf(id: string, body: Record<string, unknown>): HeldOperation {
  const held = (
    typeof body.heldOperation === 'object' && body.heldOperation !== null ? body.heldOperation : {}
  ) as Record<string, unknown>;
  const text = (value: unknown, fallback: string) => (typeof value === 'string' && value ? value : fallback);
  return {
    id,
    summary: text(held.summary, 'The operation'),
    expiresAt: text(held.expiresAt, ''),
    link: text(held.link, `${BASE}/held-operations/${id}`),
  };
}

/**
 * The header that tells the server a person, not a background refresh, made this request, so it
 * counts towards the session's idle timeout (ADR-0145). Polling sends it only while the person is
 * around; the event stream cannot send headers at all, so it never counts.
 */
export const ACTIVITY_HEADER = 'X-Studio-Activity';

/** How long after the last pointer or key press a request still counts as the person's. */
export const ACTIVITY_WINDOW_MS = 60_000;

/** When the person last used the pointer or keyboard on this page; null until they do. Monotonic, not wall time. */
let lastInteractionAt: number | null = null;

const INTERACTIONS = ['pointerdown', 'pointermove', 'wheel', 'keydown'] as const;

// One passive listener per kind for the page's whole life; recording is a single assignment.
if (globalThis.window !== undefined) {
  for (const type of INTERACTIONS) {
    globalThis.addEventListener(type, () => (lastInteractionAt = performance.now()), { capture: true, passive: true });
  }
}

/** Whether the person used the pointer or keyboard within {@link ACTIVITY_WINDOW_MS}. */
export function personIsActive(): boolean {
  return lastInteractionAt !== null && performance.now() - lastInteractionAt <= ACTIVITY_WINDOW_MS;
}

/**
 * Whether this page has seen the server confirm a sign-in (`/auth/me` or `/auth/login` succeeded).
 * A later 401 then means the session ended, as opposed to the page having started signed out.
 */
let confirmedSignedIn = false;

/** The `reason` a 401 hands the sign-in screen when this page had been signed in, so it can say the session ended. */
export const SESSION_ENDED_REASON = 'ended';

/** Reads the `XSRF-TOKEN` cookie Spring Security's `CookieCsrfTokenRepository` sets (identity-and-sessions spec). */
export function csrfToken(): string | undefined {
  return document.cookie
    .split('; ')
    .find((row) => row.startsWith('XSRF-TOKEN='))
    ?.split('=')[1];
}

/**
 * A wrong code answered to a step-up is a 401 too, but the session is fine: the person stays where they
 * are and tries again. (The attempt that ends the session answers a different problem type.)
 */
async function isWrongSecondFactor(res: Response): Promise<boolean> {
  try {
    const body = (await res.clone().json()) as { type?: unknown };
    return typeof body.type === 'string' && body.type.endsWith('/second-factor-invalid');
  } catch {
    return false;
  }
}

/** Whether this page is the sign-in page, which asks for nothing that needs a session. */
export function onLoginPage(): boolean {
  return globalThis.location.pathname.startsWith('/login');
}

/** The headers every request sends: JSON, the CSRF token on a write, the activity mark, then the caller's own. */
function requestHeaders(method: string, init?: RequestInit): Headers {
  const headers: Record<string, string> = {
    'content-type': 'application/json',
  };
  if (method !== 'GET' && method !== 'HEAD') {
    const token = csrfToken();
    if (token) headers['X-XSRF-TOKEN'] = token;
  }
  if (personIsActive()) headers[ACTIVITY_HEADER] = '1';
  // The caller's headers add to these, never replace them: replacing dropped the CSRF token.
  const merged = new Headers(headers);
  new Headers(init?.headers).forEach((value, key) => merged.set(key, value));
  return merged;
}

/** Follows the session through a response: a lost one goes to sign-in, and sign-in and sign-out are noted. */
async function trackSession(res: Response, path: string): Promise<void> {
  if (res.status === 401 && !onLoginPage() && !(await isWrongSecondFactor(res))) {
    // The session expired or was never established — bounce to the login screen.
    // A full navigation (not client-side) so every in-flight query state resets.
    globalThis.location.assign(confirmedSignedIn ? `/login?reason=${SESSION_ENDED_REASON}` : '/login');
  }
  if (res.ok && (path === '/auth/me' || path === '/auth/login')) confirmedSignedIn = true;
  if (path === '/auth/logout') confirmedSignedIn = false;
}

export async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const method = (init?.method ?? 'GET').toUpperCase();
  const res = await fetch(`${BASE}${path}`, {
    credentials: 'same-origin',
    ...init,
    headers: requestHeaders(method, init),
  });
  await trackSession(res, path);
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  const body = text ? JSON.parse(text) : {};
  if (!res.ok) throw new ApiError(res.status, body);
  const heldId = res.status === 202 ? res.headers.get(HELD_HEADER) : null;
  if (heldId) throw new OperationHeldError(heldOperationOf(heldId, body));
  return body as T;
}

/** The root every cluster-scoped query key starts from, so invalidating a cluster reaches all of it. */
export const clusterKey = (id: string, ...parts: unknown[]) => ['clusters', id, ...parts] as const;

/** The path a cluster-wide command is issued under. */
export const lifecycleBase = (clusterId: string) => `/clusters/${clusterId}`;

/**
 * A lifecycle command names the cluster, not a node, and comes back as a
 * per-node outcome. `dryRun` previews without touching any broker; `override`
 * clears the bulk cap on a destroy, which is the only kind the cap applies to.
 * A defined `dryRun` is always sent, `false` included: a real run must never be
 * left to the server's default.
 */
export interface LifecycleVars {
  dryRun?: boolean;
  override?: boolean;
}

export function lifecycleQuery(dryRun?: boolean, override?: boolean): string {
  const params = new URLSearchParams();
  if (dryRun !== undefined) params.set('dryRun', String(dryRun));
  if (override) params.set('override', 'true');
  const q = params.toString();
  return q ? `?${q}` : '';
}
