/**
 * Transport to the Artemis Studio API: `request<T>()` and the RFC 9457 `ApiError`.
 *
 * DTO types come from `schema.d.ts`, generated by `openapi-typescript` from the
 * backend's committed OpenAPI snapshot (`web/openapi.json`) — ADR-0019. Each
 * feature's `api.ts` names the DTOs it uses and holds its own hooks and query
 * keys, every cluster-scoped key under {@link clusterKey}.
 */
export const BASE = "/api/v1";

/** A parsed `application/problem+json` body. */
export class ApiError extends Error {
  readonly status: number;
  readonly type: string;
  readonly title: string;
  readonly brokerErrorKind?: string;
  readonly fieldErrors: { field: string; message: string }[];
  /**
   * The whole `problem+json` body. Handlers attach extra properties to a problem
   * — the offending token on a syntax error, the estimate and ceiling on a
   * refused query — and a message with the number left out is not something an
   * operator can act on.
   */
  readonly problem: Record<string, unknown>;

  constructor(status: number, body: Record<string, unknown>) {
    super(
      (body.detail as string) ??
        (body.title as string) ??
        `Request failed (${status})`,
    );
    this.name = "ApiError";
    this.status = status;
    this.type = (body.type as string) ?? "about:blank";
    this.title = (body.title as string) ?? "Error";
    this.brokerErrorKind = body.brokerErrorKind as string | undefined;
    this.fieldErrors =
      (body.errors as { field: string; message: string }[] | undefined) ?? [];
    this.problem = body;
  }
}

/** Reads the `XSRF-TOKEN` cookie Spring Security's `CookieCsrfTokenRepository` sets (identity-and-sessions spec). */
function csrfToken(): string | undefined {
  return document.cookie
    .split("; ")
    .find((row) => row.startsWith("XSRF-TOKEN="))
    ?.split("=")[1];
}

export async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const method = (init?.method ?? "GET").toUpperCase();
  const headers: Record<string, string> = {
    "content-type": "application/json",
  };
  if (method !== "GET" && method !== "HEAD") {
    const token = csrfToken();
    if (token) headers["X-XSRF-TOKEN"] = token;
  }
  const res = await fetch(`${BASE}${path}`, {
    credentials: "same-origin",
    headers: { ...headers, ...init?.headers },
    ...init,
  });
  if (res.status === 401 && !window.location.pathname.startsWith("/login")) {
    // The session expired or was never established — bounce to the login screen.
    // A full navigation (not client-side) so every in-flight query state resets.
    window.location.assign("/login");
  }
  if (res.status === 204) return undefined as T;
  const text = await res.text();
  const body = text ? JSON.parse(text) : {};
  if (!res.ok) throw new ApiError(res.status, body);
  return body as T;
}

/** The root every cluster-scoped query key starts from, so invalidating a cluster reaches all of it. */
export const clusterKey = (id: string, ...parts: unknown[]) => ["clusters", id, ...parts] as const;

/** The path a cluster-wide command is issued under. */
export const lifecycleBase = (clusterId: string) => `/clusters/${clusterId}`;

/**
 * A lifecycle command names the cluster, not a node, and comes back as a
 * per-node outcome. `dryRun` previews without touching any broker; `override`
 * clears the bulk cap on a destroy, which is the only kind the cap applies to.
 * A defined `dryRun` is always sent, `false` included: a real run must never be
 * left to the server's default.
 */
export interface LifecycleVars {
  dryRun?: boolean;
  override?: boolean;
}

export function lifecycleQuery(dryRun?: boolean, override?: boolean): string {
  const params = new URLSearchParams();
  if (dryRun !== undefined) params.set("dryRun", String(dryRun));
  if (override) params.set("override", "true");
  const q = params.toString();
  return q ? `?${q}` : "";
}
