// Builds the publishable package into dist/: typings from web/src/sdk, the Vite preset, and a
// package.json whose peer versions are exactly the ones this Studio build ships (ADR-0102).
//   node packages/plugin-sdk/build.mjs <version>
import { execFileSync } from 'node:child_process';
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import ts from 'typescript';

import { SHARED_LIBRARIES, packageOf } from './shared.js';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..', '..');
const dist = join(here, 'dist');
const calver = process.argv[2];
if (!/^\d{4}\.\d{2}\.\d+$/.test(calver ?? '')) {
  console.error('usage: node packages/plugin-sdk/build.mjs <YYYY.MM.PATCH>');
  process.exit(2);
}
// npm versions are semver, which forbids a leading zero: Studio 2026.09.0 is SDK 2026.9.0.
const version = calver.split('.').map((part) => String(Number(part))).join('.');

const app = JSON.parse(readFileSync(join(web, 'package.json'), 'utf8'));
const exact = (name) => {
  const v = app.dependencies[name] ?? app.devDependencies[name];
  if (!v || !/^\d/.test(v)) throw new Error(`web/package.json must pin ${name} exactly (found ${v})`);
  return v;
};
const peers = Object.fromEntries([...new Set(SHARED_LIBRARIES.map(packageOf))].map((name) => [name, exact(name)]));

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
execFileSync('npx', ['tsc', '-p', join(here, 'tsconfig.json')], { cwd: web, stdio: 'inherit' });
// tsc emits nothing for a .d.ts input; the generated API types are copied as they are.
cpSync(join(web, 'src/kernel/api/schema.d.ts'), join(dist, 'types/kernel/api/schema.d.ts'));
for (const file of ['shared.js', 'shared.d.ts', 'vite.js', 'vite.d.ts', 'README.md']) cpSync(join(here, file), join(dist, file));
writeFileSync(join(dist, 'peers.json'), JSON.stringify(peers, null, 2) + '\n');

// index.js: every value the SDK exports, by name. Module Federation builds a plugin's proxy for the
// shared SDK from this module's export list; the values themselves never run, because Studio
// provides the real module (import: false). Generated from the SDK's source, so it cannot drift.
const sdkIndex = join(web, 'src/sdk/index.ts');
const program = ts.createProgram([sdkIndex], {
  allowImportingTsExtensions: true,
  noEmit: true,
  jsx: ts.JsxEmit.ReactJSX,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  module: ts.ModuleKind.ESNext,
  target: ts.ScriptTarget.ES2022,
});
const checker = program.getTypeChecker();
const moduleSymbol = checker.getSymbolAtLocation(program.getSourceFile(sdkIndex));
const values = checker
  .getExportsOfModule(moduleSymbol)
  .filter((symbol) => {
    const target = symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
    return (target.flags & ts.SymbolFlags.Value) !== 0;
  })
  .map((symbol) => symbol.name)
  .sort();
if (!values.includes('definePlugin')) throw new Error('the SDK exports no definePlugin; the export scan is broken');
writeFileSync(
  join(dist, 'index.js'),
  [
    '// Generated by build.mjs. Artemis Studio provides this module at runtime; these names exist so a',
    "// plugin's build knows what it imports. Running a plugin outside Studio fails here, loudly.",
    'const outsideStudio = (name) => () => {',
    "  throw new Error(`${name}: @artemis-studio/plugin-sdk is provided by Artemis Studio at runtime; load this plugin in Studio.`);",
    '};',
    ...values.map((name) => `export const ${name} = outsideStudio('${name}');`),
    '',
  ].join('\n'),
);

const source = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'));
delete source.private;
delete source.scripts;
writeFileSync(
  join(dist, 'package.json'),
  JSON.stringify(
    {
      ...source,
      version,
      peerDependencies: { ...peers, vite: `>=${exact('vite').split('.')[0]}` },
      dependencies: { '@module-federation/vite': exact('@module-federation/vite') },
    },
    null,
    2,
  ) + '\n',
);
console.log(`@artemis-studio/plugin-sdk ${version} built in ${dist}`);
