import { defineConfig, type DefaultTheme } from 'vitepress';

// ADR-0061 D6. Both halves carry the sub-path: `base` prefixes every asset and
// link, and the sitemap needs absolute URLs Search Console can fetch.
const BASE = '/artemis-studio/';
const ORIGIN = `https://sudoitir.github.io${BASE}`;

const REPO = 'https://github.com/sudoitir/artemis-studio';

/** The reference tree is generated by `scripts/prepare-docs.ts`; the sidebar is not. */
function reference(labels: {
  reference: string;
  architecture: string;
  adr: string;
  changelog: string;
}): DefaultTheme.SidebarItem {
  return {
    text: labels.reference,
    items: [
      { text: labels.architecture, link: '/reference/architecture' },
      { text: labels.adr, link: '/reference/adr/' },
      { text: labels.changelog, link: '/reference/changelog/' },
    ],
  };
}

export default defineConfig({
  base: BASE,
  lang: 'en',
  title: 'Artemis Studio',
  description:
    'One console for every Apache ActiveMQ Artemis cluster you run — live topology, cross-node queues, safe message operations, and SQL over your messages.',
  cleanUrls: true,
  lastUpdated: true,
  sitemap: { hostname: ORIGIN },
  // Everything else is checked, and a broken link fails the build: the reference
  // tree is copied from `docs/` and a rename there must not ship a 404. The one
  // exception is the address Studio itself listens on, which is not ours to reach.
  ignoreDeadLinks: [/^http:\/\/localhost:8080/],
  head: [
    ['link', { rel: 'icon', href: `${BASE}img/topology.png` }],
    ['meta', { name: 'theme-color', content: '#0b7285' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'Artemis Studio' }],
    ['meta', { property: 'og:image', content: `${ORIGIN}img/topology.png` }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    // ── Google Search Console ────────────────────────────────────────────────
    // Drop the meta tag GSC gives you on the line below and uncomment it. The
    // other accepted route is the `googleXXXX.html` file: put it in
    // `site/src/public/`, which is copied verbatim, so it is served at
    // https://sudoitir.github.io/artemis-studio/googleXXXX.html
    // ['meta', { name: 'google-site-verification', content: 'PASTE_TOKEN_HERE' }],
  ],

  locales: {
    root: {
      label: 'English',
      lang: 'en',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/guide/quickstart' },
          { text: 'SQL Console', link: '/guide/sql-console' },
          { text: 'MCP', link: '/guide/mcp' },
          { text: 'Reference', link: '/reference/architecture' },
        ],
        sidebar: [
          {
            text: 'Guide',
            items: [
              { text: 'What Artemis Studio is', link: '/guide/' },
              { text: 'Quickstart', link: '/guide/quickstart' },
              { text: 'Configuration', link: '/guide/configuration' },
              { text: 'SQL Console', link: '/guide/sql-console' },
              { text: 'MCP server', link: '/guide/mcp' },
            ],
          },
          reference({
            reference: 'Reference',
            architecture: 'Architecture',
            adr: 'Decision records',
            changelog: 'Changelog',
          }),
        ],
        editLink: { pattern: `${REPO}/edit/main/site/src/:path`, text: 'Edit this page on GitHub' },
        docFooter: { prev: 'Previous', next: 'Next' },
        outline: { label: 'On this page', level: [2, 3] },
      },
    },

    zh: {
      label: '简体中文',
      lang: 'zh-Hans',
      description: '一个控制台，管理你运行的每一个 Apache ActiveMQ Artemis 集群——实时拓扑、跨节点队列、安全的消息操作，以及对消息的 SQL 查询。',
      themeConfig: {
        nav: [
          { text: '指南', link: '/zh/guide/quickstart' },
          { text: 'SQL 控制台', link: '/zh/guide/sql-console' },
          { text: 'MCP', link: '/zh/guide/mcp' },
          { text: '参考', link: '/reference/architecture' },
        ],
        sidebar: [
          {
            text: '指南',
            items: [
              { text: 'Artemis Studio 是什么', link: '/zh/guide/' },
              { text: '快速开始', link: '/zh/guide/quickstart' },
              { text: '配置', link: '/zh/guide/configuration' },
              { text: 'SQL 控制台', link: '/zh/guide/sql-console' },
              { text: 'MCP 服务器', link: '/zh/guide/mcp' },
            ],
          },
          reference({
            reference: '参考（英文）',
            architecture: '架构',
            adr: '架构决策记录',
            changelog: '更新日志',
          }),
        ],
        editLink: { pattern: `${REPO}/edit/main/site/src/:path`, text: '在 GitHub 上编辑此页' },
        docFooter: { prev: '上一页', next: '下一页' },
        outline: { label: '本页目录', level: [2, 3] },
        darkModeSwitchLabel: '外观',
        returnToTopLabel: '回到顶部',
        sidebarMenuLabel: '菜单',
        langMenuLabel: '切换语言',
      },
    },

    fa: {
      label: 'فارسی',
      lang: 'fa',
      dir: 'rtl',
      description:
        'یک کنسول برای همهٔ کلاسترهای Apache ActiveMQ Artemis شما — توپولوژی زنده، صف‌ها در همهٔ نودها، عملیات امن روی پیام‌ها، و SQL روی پیام‌ها.',
      themeConfig: {
        nav: [
          { text: 'راهنما', link: '/fa/guide/quickstart' },
          { text: 'کنسول SQL', link: '/fa/guide/sql-console' },
          { text: 'MCP', link: '/fa/guide/mcp' },
          { text: 'مرجع', link: '/reference/architecture' },
        ],
        sidebar: [
          {
            text: 'راهنما',
            items: [
              { text: 'Artemis Studio چیست', link: '/fa/guide/' },
              { text: 'شروع سریع', link: '/fa/guide/quickstart' },
              { text: 'پیکربندی', link: '/fa/guide/configuration' },
              { text: 'کنسول SQL', link: '/fa/guide/sql-console' },
              { text: 'سرور MCP', link: '/fa/guide/mcp' },
            ],
          },
          reference({
            reference: 'مرجع (انگلیسی)',
            architecture: 'معماری',
            adr: 'سوابق تصمیم‌های معماری',
            changelog: 'تغییرات',
          }),
        ],
        editLink: { pattern: `${REPO}/edit/main/site/src/:path`, text: 'ویرایش این صفحه در GitHub' },
        docFooter: { prev: 'قبلی', next: 'بعدی' },
        outline: { label: 'در این صفحه', level: [2, 3] },
        darkModeSwitchLabel: 'ظاهر',
        returnToTopLabel: 'بازگشت به بالا',
        sidebarMenuLabel: 'منو',
        langMenuLabel: 'تغییر زبان',
      },
    },
  },

  themeConfig: {
    logo: '/img/topology.png',
    search: { provider: 'local' },
    socialLinks: [{ icon: 'github', link: REPO }],
    footer: {
      message:
        'Apache-2.0. Apache ActiveMQ and Apache ActiveMQ Artemis are trademarks of the Apache Software Foundation. Artemis Studio is an independent project, not produced by, endorsed by, or affiliated with the ASF.',
      copyright: `<a href="${REPO}">github.com/sudoitir/artemis-studio</a>`,
    },
  },
});
