@startuml
title <size:24>ArtemisStudioApplication</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("ArtemisStudioApplication_boundary", "ArtemisStudioApplication", $tags="") {
  Container_Boundary("ArtemisStudioApplication.ArtemisStudioApplication_boundary", "ArtemisStudioApplication", $tags="") {
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Settings, "Settings", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "Event stream", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "Broker connectivity", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, "Data governance", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, "Broker events", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "Clusters", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, "API tokens", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "MCP server", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "Scraping", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, "Alerting", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Messages, "Messages", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Metrics, "Metrics", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Queues, "Queues", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Resources, "Resources", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, "Broker configuration", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Flow, "Flow", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Routing, "Routing", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, "SQL console", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Triage, "Triage", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, "Request-reply tracing", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Core, "Core", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "Scheduled jobs", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "Plugin contract", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Security, "Security", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Singlesignon, "Single sign-on", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "Audit log", $techn="Module", $descr="", $tags="", $link="")
    Component(ArtemisStudioApplication.ArtemisStudioApplication.Passwordlogin, "Password login", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "listens to", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.APItokens, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "listens to", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "listens to", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Alerting, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Alerting, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Queues, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconfiguration, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Clusters, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Queues, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Flow, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, ArtemisStudioApplication.ArtemisStudioApplication.Security, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Messages, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Metrics, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Metrics, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Metrics, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Metrics, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Passwordlogin, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Passwordlogin, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Passwordlogin, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Passwordlogin, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Queues, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Requestreplytracing, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Resources, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Queues, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Routing, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Datagovernance, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Messages, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Queues, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.SQLconsole, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Eventstream, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Scheduledjobs, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Scraping, ArtemisStudioApplication.ArtemisStudioApplication.Settings, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Security, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Security, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Settings, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Settings, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Settings, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Singlesignon, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Singlesignon, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Alerting, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Auditlog, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Brokerconnectivity, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Brokerevents, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Clusters, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Core, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.MCPserver, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Plugincontract, "depends on", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Resources, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Scraping, "uses", $techn="", $tags="", $link="")
Rel(ArtemisStudioApplication.ArtemisStudioApplication.Triage, ArtemisStudioApplication.ArtemisStudioApplication.Security, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml
